### ISSUE TITLE
really cool  webrtc project for pythoner

### ISSUE THREAD

**Issue by notedit** [jlaine/aiortc#1]
looking forward a test  👍

**Comment by jlaine** [comment]
Glad you like it! If you want a quick test, you can run the provided `examples/server/server.py` (requires aiohttp) and point your browser at http://localhost:8080

**Comment by notedit** [comment]
yes,  will give a test.  we now use mediasoup https://github.com/versatica/mediasoup,  a well designed webrtc sfu.   really happy we will have a webrtc server in python world.

**Comment by jlaine** [comment]
Cool! Be aware that codec negotiation and video support still needs to be implemented, for now it's hard-wired to audio/PCMA, so far I have been focusing on getting the lower layers right.

Ideally I'd like to keep a very basic interface for the media API as in : you subclass AudioStreamTrack / VideoStreamTrack to provide your own sources. That should give you the greatest latitude to implement your own mixing / forwarding / whatever logic.

**Comment by notedit** [comment]
that will be cool,  i will try to write some sfu server when you finished the api
