### ISSUE TITLE
Video size mismatch

### ISSUE THREAD

**Issue by nickaknudson** [jlaine/aiortc#10]
I'm working on sending and receiving video streams between python clients.

I am having an issue with a mismatch between the amount of bytes that I am sending and the amount that I am receiving. I was originally sending a 240h x 960w frame which is 345600 bytes, but on the receiving side I am getting 368640 bytes which I am then unable to marshal into the correct frame size.

I have simplified the example by sending a 6h x 8w frame which is only 72 bytes, but on the receiving side I am getting 864 bytes.

I think this might have something to do with the compression. I would appreciate some advice as to where to look.

Here is my working branch. I started by modifying cli.py https://github.com/nickaknudson/aiortc/blob/testing/examples/datachannel-cli/cli.py

**Comment by nickaknudson** [comment]
It looks like `o_buf` is getting its size changed here:

https://github.com/jlaine/aiortc/blob/master/aiortc/codecs/vpx.py#L152

**Comment by nickaknudson** [comment]
Here's some example debug output around line 152:
```
o_buf before line 152: len=72 o_pos=0 o_stride=8
o_buf after  line 152: len=160 o_pos=0 o_stride=8
o_buf before line 152: len=160 o_pos=8 o_stride=8
o_buf after  line 152: len=248 o_pos=8 o_stride=8
o_buf before line 152: len=248 o_pos=16 o_stride=8
o_buf after  line 152: len=336 o_pos=16 o_stride=8
o_buf before line 152: len=336 o_pos=24 o_stride=8
o_buf after  line 152: len=424 o_pos=24 o_stride=8
o_buf before line 152: len=424 o_pos=32 o_stride=8
o_buf after  line 152: len=512 o_pos=32 o_stride=8
o_buf before line 152: len=512 o_pos=40 o_stride=8
o_buf after  line 152: len=600 o_pos=40 o_stride=8
o_buf before line 152: len=600 o_pos=48 o_stride=4
o_buf after  line 152: len=644 o_pos=48 o_stride=4
o_buf before line 152: len=644 o_pos=52 o_stride=4
o_buf after  line 152: len=688 o_pos=52 o_stride=4
o_buf before line 152: len=688 o_pos=56 o_stride=4
o_buf after  line 152: len=732 o_pos=56 o_stride=4
o_buf before line 152: len=732 o_pos=60 o_stride=4
o_buf after  line 152: len=776 o_pos=60 o_stride=4
o_buf before line 152: len=776 o_pos=64 o_stride=4
o_buf after  line 152: len=820 o_pos=64 o_stride=4
o_buf before line 152: len=820 o_pos=68 o_stride=4
o_buf after  line 152: len=864 o_pos=68 o_stride=4
```

**Comment by nickaknudson** [comment]
Well it turns out the correct bytes are all there at the beginning. There are just a lot of extra bytes.

Workaround is to calculate the number of expected bytes and read those from `frame.data` throwing away the rest of the bytes.

Not sure if this is expected behavior or not.

```
async def consume_video(track):
    while True:
        try:
            frame = await track.recv()
            num_expected_bytes = int(frame.width * frame.height * 3/2)
            img_yuv_bytes = frame.data[0:num_expected_bytes]
            img_yuv_flat = np.frombuffer(img_yuv_bytes, np.uint8)
            img_yuv = img_yuv_flat.reshape((int(frame.height*3/2), frame.width))
            img_bgr = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2BGR_YV12)
            cv2.imwrite('image.png',img_bgr)
        except Exception as e:
            print(e)
```

**Comment by jlaine** [comment]
I don't have a proper internet connection / laptop for a few days, but I'll definitely get back to you. If you demo can easily be run, this should be easy to reproduce and debug.

Maybe you could clean up your demo, document it (its own Readme.md) and we can include it with the examples, instead of hacking the unrelated data channels demo?

**Comment by nickaknudson** [comment]
Opened #11
