### ISSUE TITLE
Recieved video muting for 1-2 minutes before starting to play

### ISSUE THREAD

**Issue by tobiasfriden** [jlaine/aiortc#100]
Hello,

I am trying to send a camera stream with aiortc through a self-implemented golang SFU (using github.com/pions/webrtc). The intended setup is aiortc client (streaming video) -> SFU -> browser client (displaying video).
However I have an issue where the recieved video is first unmuted for ~3 seconds, then muted for 1-2 minutes before starting to play. I have tried some different combinations:

1. Using OpenCV `cv2.VideoCapture` to stream the video as in #99 . This results in the video being muted for around 1-2 minutes and then playing.
2. Using `aiortc.MediaPlayer` with a mp4-file. Same result as 1.
3. Using `aiortc.MediaPlayer('0', format='avfoundation', options={'framerate': '30'})`. So far this one does not work (never unmutes, even after several minutes). However, this option works in the Webcam example.
4. Using a browser as client instead of aiortc. This works fine without any muting.

Since 4 works I suspect there might be something aiortc related. Looking at the [specification](https://w3c.github.io/mediacapture-main/#track-muted) muted seems to mean that there is no video avaliable in the stream, however using wireshark I can see UDP traffic being both sent to the SFU and forwarded to the browser.

**Comment by jlaine** [comment]
As there are elements in your setup which are unrelated to `aiortc` (your use of cv2.VideoCapture, the SFU), please reproduce this based on one of the aiortc examples, otherwise I cannot help you.

**Comment by tobiasfriden** [comment]
Managed to get `aiortc` based SFU working, and now it works fine! Works with both `cv2.VideoCapture` and ` aiortc.MediaPlayer('0', format='avfoundation', options={'framerate': '30'})`, however the first option seems to be much better latency-wise.

**Comment by tamert** [comment]
hello @tobiasfriden, I saw your code
I am trying and I added this code on my created listener.js 

```javascript
    pc = new RTCPeerConnection(config);
    pc.addTransceiver("video", { direction: "recvonly" })
    pc.addTransceiver("audio", { direction: "recvonly" })
```
 however, only one frame showed html video element ...
  
 can you send your listener html and js code ? I did't find my problem solve

**Comment by tamert** [comment]
I solved and I understood.. Mux is not necessary for me
only track is enough :) 
```python
    @pc.on("track")
    async def on_track(track):
        log_info("broadcast: Track %s received" % track.kind)
        senderStream.add(track)
 ```
