### ISSUE TITLE
RTSP reading frame error: RTP missed xxx packets

### ISSUE THREAD

**Issue by shawntian90** [jlaine/aiortc#101]
hi,

I run the example of *webcam* and modify the video source from local `/dev/video0` to `rstp://ip_address` as data source of `MediaPlayer` like following, which was mentioned by #70 

```python

# open webcam
    options = {'video_size': '640x480'}
    if platform.system() == 'Darwin':
        player = MediaPlayer('default:none', format='avfoundation', options=options)
    else:
        # I modified this line
        # player = MediaPlayer('/dev/video0', format='v4l2', options=options)
        player = MediaPlayer('rtsp://ip_address')
```

And it show the error:

```
$ python webcam.py
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
max delay reached. need to consume packet
RTP: missed 32 packets
error while decoding MB 55 42, bytestream -9
Increasing reorder buffer to 1
ICE connection state is checking
ICE connection state is completed
error while decoding MB 55 42, bytestream -9
max delay reached. need to consume packet
RTP: missed 2018 packets
max delay reached. need to consume packet
RTP: missed 3 packets
error while decoding MB 34 59, bytestream -11
max delay reached. need to consume packet
RTP: missed 56 packets
...
```

Anyone knows this problem?

I think it usually cause by rtsp IP camera's buffer, and may be resolved by reading the frames as quickly as possible. Am I right?

Thanks!

Best,
Shawn

**Comment by shawntian90** [comment]
Additionally, what I want to is:

1. Read the video from `IP Camera via RTSP`;
2. Do some `Frame Transformation` like drawing human body detection boxes to the origin video frame, etc;
3. Show the boxes to user via browser through WebRTC protocal.

It confused me a lot about how to convert RTSP frames to WebRTC correctly.

**Comment by jlaine** [comment]
Do you have an RTSP url which I can use to try and reproduce the issue please?

**Comment by jlaine** [comment]
Also, could you try adding `'rtsp'` in the following line and report whether the behaviour changes?

https://github.com/jlaine/aiortc/blob/d120d4ce90f0832b68ef1e0ed7a503a31608d26e/aiortc/contrib/media.py#L201

By default, `MediaPlayer` throttles the rate at which it reads the input, as otherwise reading from a file would pull the whole file into memory and sending it out as fast as possible. The chang I suggest will disable the throttling.

**Comment by shawntian90** [comment]
@jlaine 
You can try this one `rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov`

The RTSP both include video and audio, but in my case I only need video.

**Comment by jlaine** [comment]
If the RTSP includes both audio and video, you should either send them both, or manually consume the audio otherwise it will be buffered forever

**Comment by jlaine** [comment]
The timestamps on the video frames for the stream you provided look pretty bogus, they go back and forth in time:

```
<av.VideoFrame #0, pts=0 yuv420p 240x160 at 0x7f0952eeb8d0>
<av.VideoFrame #1, pts=-18750 yuv420p 240x160 at 0x7f0952eeb868>
<av.VideoFrame #2, pts=-15060 yuv420p 240x160 at 0x7f0952eebb40>
<av.VideoFrame #3, pts=-11280 yuv420p 240x160 at 0x7f0952eebdb0>
<av.VideoFrame #4, pts=-7500 yuv420p 240x160 at 0x7f0952eeb2b8>
<av.VideoFrame #5, pts=-3810 yuv420p 240x160 at 0x7f0952ed32b8>
<av.VideoFrame #6, pts=-30 yuv420p 240x160 at 0x7f0952eeb8d0>
<av.VideoFrame #7, pts=3750 yuv420p 240x160 at 0x7f0952eebee8>
<av.VideoFrame #8, pts=7440 yuv420p 240x160 at 0x7f0952eebe80>
<av.VideoFrame #9, pts=11220 yuv420p 240x160 at 0x7f0952eebd48>
```

Do you have another stream I can look at?

**Comment by jlaine** [comment]
Closing due to lack of response

**Comment by huyxdong** [comment]
@jlaine Have you solved this problem yet?
