### ISSUE TITLE
Hi, jlaine

### ISSUE THREAD

**Issue by walle-z** [jlaine/aiortc#103]
Hi Jeremy Lainé,
I want to know can aiortc receive remotevideo stream and display?
Thank you

**Comment by walle-z** [comment]
Hi Jlaine,
I want to know wether aiortc can accomplish two-way video chat

**Comment by jlaine** [comment]
You'll have to be a bit more explicit about what you are trying to achieve if you want help.

aiortc is able to send and receive video - yes. 

On the other hand it has no built-in concept of "display". Your code will receive the decoded video frames, what you do with it is up to you.

**Comment by walle-z** [comment]
@jlaine 
Thank you very much.
Your answer is important and helpful to me.
Aiortc helped me a lot.It is awesome.
Thank you again.Jeremy.
