### ISSUE TITLE
Video playback delay in server example

### ISSUE THREAD

**Issue by mikelibg** [jlaine/aiortc#104]
Hi, I am experiencing a delay, especially in chrome web browser while running the server example as is. I am running the server and on the same network (wifi) trying to view the video on a web client. It seems that over time there is an "accumulated" delay of the video, although i do not apply any filter on the frames of the video data so the only delay here is the round trip of the frame.

Should I fine-tune the frame rate of the video data that is being sent?
Maybe the issue is with a queue of the frames to render on the client side, in which case, can i drop the queue?

Thanks!

**Comment by jlaine** [comment]
Before trying to change things, let's get a better understanding of what is going on. From whatI understand you are running the browser and aiortc on two separate machines, right? If so, what does the CPU usage look like on the aiortc side? Is the CPU maxed out?

**Comment by jlaine** [comment]
One thing you might look into is the resolution : by default the `server` examples picks whatever the browser's defaults are. You can try forcing a 640x480 resolution and see whether things improve.

Dynamically decimating the frame rate in case the CPU budget is exceeded might also be an interesting option, but I haven't had a chance to look at how browsers usually implement this.

**Comment by mikelibg** [comment]
I will try to retest that. When I observed the delay I experimented with the resolution as well but the delay was still there, that's why I asked about the frame rate as it seemed like an option to try.

**Comment by mikelibg** [comment]
Retested with 640x480 with edge detection (server and client on the same machine), CPU on 70%.
Started normally and quickly got to 9 seconds of delay after one spike of CPU to around 100% for few seconds due to opening of another software.

Tried the same with 640x480 without any frame modification and it worked fine for a while. Then decided to do the same spike of CPU to 100% for a few seconds. After the CPU dropped back to about 60% a delay of 3 seconds remained for a long time. (Tried several times, sometimes the delay caught up but sometimes the delay remains for a long time).

**Comment by jlaine** [comment]
OK that last experiment is a very good one. To keep the number of moving parts to a minimum I suggest we stick to the "no transformation" use case going forward, as this really tests aiortc's core without involving OpenCV. I would also suggest disabling audio to focus exclusively on video for now.

Bear in mind that the setup with browser + aiortc on the same machine is fairly agressive : you are running a full browser as well as 2 encoders and 2 decoders on the same machine. Nevertheless on my machine (Linux on Core i7 / 2.7GHz) it works fine. My total CPU usage is around ~60%, with the browser consuming about 2x more CPU than aiortc. Could you have a look at who is using the most CPU (aiortc or the browser)?

My initial thought is that if there is a bottleneck in aiortc, it would be on the encoding side. I assume you stayed with the default codec (VP8)? If so there is one knob you can turn : 

https://github.com/jlaine/aiortc/blob/535fb616db3225763142e5230089c3123f9f63ff/aiortc/codecs/vpx.py#L235

If you change the `-6` to something lower such as `-8`, `-10` or even `-12` it will instruct VP8 to reduce encoding complexity in favour of lower CPU usage. The WebRTC.org codebase (used by Chrome + Firefox) uses `-6`, which is why I adopted it for `aiortc`.

**Comment by mikelibg** [comment]
I see the exact opposite on my side. The server (aiortc) takes double CPU then the browser client:

![image](https://user-images.githubusercontent.com/2489850/49498861-21feaa00-f875-11e8-8cfd-63d57db1181d.png)

![image](https://user-images.githubusercontent.com/2489850/49498933-54100c00-f875-11e8-929e-8ab79bd8ade4.png)

**Comment by jlaine** [comment]
@mikelibg have you gotten any further in understanding / reproducing the issue? The CPU usage I'm seeing is very different from what you describe, so I'm wondering if there is anything OS X - specific going on here.

**Comment by mikelibg** [comment]
@jlaine I am currently on a vocation and will be able to play with reducing the encoding and rerunning it again in a couple of days. Will update on the progress.

**Comment by jlaine** [comment]
Hi @mikelibg any news on this?

**Comment by mikelibg** [comment]
Tried running again but probably having some linking issues with ffmpeg libraries now:

  File "server.py", line 10, in <module>
    from av import VideoFrame
  File "/Users/mike/miniconda3/lib/python3.6/site-packages/av/__init__.py", line 9, in <module>
    from av._core import time_base, pyav_version as __version__
ImportError: dlopen(/Users/mike/miniconda3/lib/python3.6/site-packages/av/_core.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/ffmpeg/lib/libswresample.2.dylib
  Referenced from: /Users/mike/miniconda3/lib/python3.6/site-packages/av/_core.cpython-36m-darwin.so
  Reason: image not found

Will try to resolve it in order to run the tests.

**Comment by mikelibg** [comment]
Just an update, I ran the server on Ubuntu 18.04.2 LTS with i7-6700 3.4Ghz and 16GHz RAM and i do not see (meanwhile) the delays i had on my mac. And the CPU usage is similar to what you mention where the browser is taking x2 CPU than aiortc.

**Comment by jlaine** [comment]
Thanks so much for taking the time to provide your feedback. It looks like there is something odd on OS X, but I'm pretty sure it's outside aiortc itself..

**Comment by tartavull** [comment]
I can reproduce all of @mikelibg issues in OS X.

**Comment by jlaine** [comment]
H.264 is a poor substitute for vp8 (we cannot adapt the bandwidth on the fly for instance, it's supported by fewer browsers..) so I'd vote no as a general rule. As I don't have access to an OS X box you're welcome to investigate the issue.

**Comment by tartavull** [comment]
Thanks for the quick response, I was trying to just test another codec to if there is some correlation.
I tried doing this modification to webcam.py, is there a less hacky way of only allow for h.264?

 ```
   answer = await pc.createAnswer()
    from aiortc.sdp import SessionDescription
    parsed = SessionDescription.parse(answer.sdp)
    parsed.media[0].rtp.codecs.pop(0)
    parsed.media[0].fmt.pop(0)
    new_answer = RTCSessionDescription(
            sdp=str(parsed),
            type=answer.type)
    await pc.setLocalDescription(new_answer)
```
but the browser didn't like it, is this what  you refer to less support from browsers?
```
InvalidAccessError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to set remote video description send parameters.
```
I'm using `Google Chrome | 72.0.3626.121 (Official Build) (64-bit)`.

**Comment by jlaine** [comment]
The proper way to influence codec selection is to use `RTCRtpTransceiver.setCodecPreferences`:

https://aiortc.readthedocs.io/en/latest/api.html#aiortc.RTCRtpTransceiver.setCodecPreferences

You can find an example in aiortc's test suite:

https://github.com/aiortc/aiortc/blob/bb4f2e8b1912db2723b9390d1c5c8742d36d63f3/tests/test_rtcpeerconnection.py#L2162

This examples re-arranges the codec order to prefer H.264 to VP8. You can also go even further and completely remove vp8.

**Comment by tartavull** [comment]
Thanks, performance is slightly better with H264, my laptop is now able to handle 640x480 without a build up of latency but not any higher resolution.
I was also planning on using a raspberry pi to stream video to my laptop over a local network, but performance there is worse than my laptop. I didn't realize how cpu intensive would the task be.

**Comment by tartavull** [comment]
I just tried the webrtc uv4l demo on a raspberry pi, and it was able to stream 1280x720 @ 30 fps with very low latency 200ms or less using 20% of cpu resources when using the h264 hardware encoder -- it almost feels magical. When disabling hardware encoding it uses 70% of the cpu.
I'm wondering what is causing the performance difference with aiortc webcam demo.

[1] https://www.linux-projects.org/uv4l/webrtc-extension/

**Comment by jlaine** [comment]
You answered your own question: hardware acceleration. PyAV currently doesn't use hardware acceleration but you're welcome to go polish the pull request which enables it so it can be merged.

**Comment by tartavull** [comment]
Thanks for so much help @jlaine, aiortc is great, and improving the performance would really matter for my project.
I agree that hardware acceleration is a big factor, the other thing I noticed is when comparing non hardware accelerated uv4l to aiortc there was also a huge performance difference.
Sadly, uv4l seems to be closed source. I'm wondering if you have any intuitions on what might be causing this difference?

**Comment by razvanphp** [comment]
As PyAV decided [here](https://github.com/mikeboers/PyAV/pull/331#issuecomment-548110744) not to merge hw acceleration, another path would be to fork and refactor aiortc media pipeline to bitstream the H264 stream from a HW accelerated RPi source, v4l2 or raspivid.

**Comment by SoundsSerious** [comment]
Finding this issue to be a weakpoint in my usage of aiortc on a Raspberry Pi 4. I'm still root causing my particular case but it seems PyAV's lack of HW Acceleration hamstring's it's use on embedded hardware.

A few other options that crossed my mind, would be to capture streams from other command-line utilities and send them through a MediaPlayer subclass.

It seems there's some new interest in PyAV going the hwacceleration route, there is a fork of it with HW acceleration built in so perhaps that's worth a look as well.
https://github.com/PyAV-Org/PyAV/issues/307#issuecomment-391836207

**Comment by SoundsSerious** [comment]
@jlaine any way you might forsee the use of an ffmpeg subprocess to pipe into the `aiortc` encoders section? 

On a raspberrypi 4 everything is working great except for video, would be a great option to allow a user a custom encoding option built around ffmpeg. This lets us get around the GIL with an extra process doing the encoding work, and lets us separate concern & dependence on other libraries. 

Having dug around PyAV and aiortc a few key interface questions might be:
1) Do you need to use PyAV frames
2) Could you use an ffmpeg format like UNIX / PIPES or STDOUT
3) Where would we drop-in a codec for this?

**Comment by ivorhoulker** [comment]
Was this worked out already? I'm also trying to figure out how to get aiortc to use the hardware encoding on a raspberry pi 4 (although I'm using it via mediasoup-client-aiortc). Not sure where to look for help with such a specific combination of stuff.

**Comment by jlaine** [comment]
Commenting on a closed issue tends not to give great results
