### ISSUE TITLE
JSON.parse error in examples/server

### ISSUE THREAD

**Issue by yschermer** [jlaine/aiortc#105]
I am trying out this example: https://github.com/jlaine/aiortc/tree/master/examples/server 

I can get to the server. But when I try to start either audio/video I get the following error:
**SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data**

I am seeing this error on my system (Debian), I suspect it might have something to do with that:
**av.AVError: [Errno 1094995529] Invalid data found when processing input: 'demo-instruct.wav'**

Extra remarks:
- demo_instruct.wav is present

Can somebody help me further with this?

**Comment by jlaine** [comment]
The JSON error is definitely a symptom and not the root cause. I'm running Debian/buster and don't see this issue, so I'm wondering whether the WAV file got corrupted somehow?

**Comment by yschermer** [comment]
Downloaded the WAV file again, and that seemed to do it. Thanks!

**Comment by jlaine** [comment]
Thanks for letting me know you solved the issue. For my information, how did you download the file originally? I would expect a git clone to be byte-perfect.

**Comment by yschermer** [comment]
Sorry for the late-response. The thing was, I didn't clone it. Just downloaded it manually, and somewhere there I must have made a mistake. 
Anyhow, the clone is probably fine.

**Comment by jlaine** [comment]
OK, thanks for your feedback!
