### ISSUE TITLE
INFO:ice:Connection(0) Consent to send expired

### ISSUE THREAD

**Issue by sarkarchandan** [jlaine/aiortc#106]
Hi Jeremy,

I have a question regarding a particular behaviour of aiortc. This is with reference to the below log messages
publisher    | INFO:aiohttp.access:192.168.100.19 [11/Dec/2018:18:54:00 +0000] "POST /receive_client_offer HTTP/1.1" 200 1469 "-" "-"
publisher    | INFO:ice:Connection(1) Check CandidatePair(('172.23.0.3', 39310) -> ('192.168.100.19', 59357)) State.FROZEN -> State.WAITING
publisher    | INFO:ice:Connection(1) Check CandidatePair(('172.23.0.3', 39310) -> ('192.168.100.19', 59357)) State.WAITING -> State.IN_PROGRESS
publisher    | INFO:ice:Connection(1) Check CandidatePair(('172.23.0.3', 39310) -> ('192.168.100.19', 59357)) State.IN_PROGRESS -> State.SUCCEEDED
publisher    | INFO:ice:Connection(1) ICE completed
publisher    | INFO:ice:Connection(0) Consent to send expired

Could you please let me know what may cause this statement "Consent to send expired" ? What does it mean ?
It sounds like a problem and when it happens video stream stops which is expected I guess.

Thanks in advance.

**Comment by jlaine** [comment]
ICE implementations used for WebRTC are required to periodically check "consent" from the remote party to send them media. This is done using STUN binding requests, see:

https://tools.ietf.org/html/rfc7675

This is implemented in `aioice` here:

https://github.com/jlaine/aioice/blob/32db5d715c26eb79c6506ce226e2db72798b2618/aioice/ice.py#L748

"Consent to send expired" means the remote party is no longer replying to the STUN requests, and as such we must no longer send them media.

Could you re-run your example in verbose mode and include the full log please, as I don't see the STUN requests / responses in your log (and there must have been at least one for the ICE candidate pair to have been valided)? Also what's the endpoint facing aiortc (browser, other)?

**Comment by sarkarchandan** [comment]
Thanks for the response Jeremy.
I would try to run it in VERBOSE shortly and share the outcome.

Meanwhile, one quick question though. Is there a way to disable/bypass the periodic consent checking utility ?

In my implementation I indeed don't have a STUN server because I am testing the setup within my private network only. 

The other end aiortc is talking to is indeed a browser page hosted by Node.JS (let's call it a client). But there is one more thing. In between aiortc and the client there is another Node.JS web app (let's call it mediator) which simply transfers the RTCSessionDescription offer generated by the client to aiortc and subsequently the answer generated by aiortc back to the client, all over POST messages and responses. That's pretty much the one thing which it does. The only thing which is different in your Webcam example is that your client directly sends a POST message to aiortc and receives the response. In my case it does the same via this mediator but what it receives is ultimately same as your Webcam example.

This is a simple setup that I am testing and all within same network for now. That's why I am wondering how I can make this work bypassing this consent checking thing.

Could you please advise ?

**Comment by jlaine** [comment]
Bypassing the content check is not a solution, as the absence of a response is a symptom of broken connectivity (possibly an over zealous firewall?). There is no option to disable the content check, as this is a spec violation. If you absolutely want to go that way, you'll have to hack the `aioice` code.

I didn't fully understand your hosting arrangement, but the HTTP part is not relevant, all that matters the parties participating in the actual media exchange : aiortc and the browser. Try to reproduce the issue with the simple "server" example, which has a convenient `-v` option to enable verbose debugging.

**Comment by sarkarchandan** [comment]
Thanks a lot for your response.
