### ISSUE TITLE
Set Encoding/Decoding for RtpSender/RtpReceiver

### ISSUE THREAD

**Issue by quentinwendegass** [jlaine/aiortc#108]
Hi Jeremy,
I can't figure out how to set the encoding and decoding for the audio tracks to PCMA/PCMU. Default it is set to opus. I noticed that RtpParameters specify the codec, but how can I tell the RtpSender/RtpReceiver to use a specific codec?

**Comment by jlaine** [comment]
Hi @quentinwendegass I have added the following methods:

- `RTCRtpSender.getCapabilities`
- `RTCRtpTransceiver.setCodecPreferences`

You can combine these two to set PCMA then PCMU as the preferences for a specific transceiver.

```python
# create a peer connection and add an audio track
pc = RTCPeerConnection()
pc.addTrack(AudioStreamTrack())

# set PCMU and PCMA as the only available codecs
capabilities = RTCRtpSender.getCapabilities('audio')
preferences = list(filter(lambda x: x.name == 'PCMA', capabilities.codecs))
preferences += list(filter(lambda x: x.name == 'PCMU', capabilities.codecs))
transceiver = pc1.getTransceivers()[0]
transceiver.setCodecPreferences(preferences)
```
