### ISSUE TITLE
Help streaming audio to/from client/server

### ISSUE THREAD

**Issue by yschermer** [jlaine/aiortc#109]
I am trying to create live communication (video and audio) between a Raspberry Pi and a web interface. So far, I have only managed to record audio on the client, that is, the web interface. And then, send the recorded audio to the server, the Raspberry Pi. 
I am trying to figure out how to stream audio to the server (and/or client) instead. I have tried looking at PyAv and more at the examples here, but it's not really helping.

Does someone maybe know the necessary steps I would have to take in order to accomplish this?

**Comment by jlaine** [comment]
I'm afraid you'll have to explain a little more what you are trying to achieve, I'm a bit confused by your client / server teminology. Who are the two parties in your example and where is aiortc running?

I suggest you start by trying the various examples provided with `aiortc` to determine which one is closest to your desired setup.

**Comment by yschermer** [comment]
One party is the Raspberry Pi, and the other is just a regular Windows machine. Aiortc runs on the RPi.
Both devices have a microphone as well as speakers. And what I basically want is pretty much a telephone communication between them.

Now, I have worked with and modified the server example which allowed me to record audio and send that from the Windows machine to the Raspberry Pi. That part worked out fine. But, this ofcourse isn't realtime which is what I want.

Unfortunately, I haven't been able to find an example that does realtime audio between two machines.

Now, I think I can do realtime with the help of RTP. I have looked at the docs in here, but I am a little in need of a small example that could me push in the right direction. Or perhaps there's a better approach?

**Comment by yschermer** [comment]
I have used the webcam example, and basically the only thing I changed is this:
`player = MediaPlayer("hw:1,0", format='alsa')`.

Now I constantly get the following error:

```
cannot set channel count to 2 (Invalid argument)
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "web.py", line 43, in offer
    player = MediaPlayer("hw:1,0", format='alsa')
  File "/usr/local/lib/python3.5/dist-packages/aiortc/contrib/media.py", line 184, in _init_
    self.__container = av.open(file=file, format=format, mode='r', options=options)
  File "av/container/core.pyx", line 275, in av.container.core.open
  File "av/container/core.pyx", line 227, in av.container.core.Container._cinit_
  File "av/container/core.pyx", line 129, in av.container.core.ContainerProxy._init_
  File "av/container/core.pyx", line 195, in av.container.core.ContainerProxy.err_check
  File "av/utils.pyx", line 105, in av.utils.err_check
av.AVError: [Errno 5] Input/output error: 'hw:1,0' (16: alsa)
```
Entering this in the terminal works: `ffmpeg -f alsa -ac 1 -i hw:1 -t 30 out.wav`. It only works when I add the option `-ac 1` though. 

I believe this is the reason why it doesn't work. Is it possible to set an audiochannel programmatically?

**Comment by yschermer** [comment]
Thanks that did it!

**Comment by yschermer** [comment]
I have now also implemented the communication from website to the Raspberry Pi using mediarecorder:

`recorder = MediaRecorder('hw:0', format='alsa')`

However, now I keep getting the following error:

`sample format 0x15002 is not supported`

I tried to explicitely add the format in asoundrc.conf, but to no avail. On internet I read that it might have to do with the sample rate

**Comment by jlaine** [comment]
We are getting further and further off topic. I unfortunately cannot act as the free support hotline for PyAV, FFmpeg and now possibly alsa. Please do some research of your own and open a new issue when there is a definite bug in aiortc.
