### ISSUE TITLE
Working locally but not on cloud. (Server Example)

### ISSUE THREAD

**Issue by faizankarim** [jlaine/aiortc#110]
server example runs smoothly when i try locally . but do not work when i try it on cloud. both in chrome and firefox.

web_1  | DEBUG:ice:controlled - new -> checking
web_1  | INFO:ice:Connection(2) Check CandidatePair(('192.168.64.2', 53491) -> ('192.168.100.5', 39121)) State.FROZEN -> State.WAITING
web_1  | INFO:ice:Connection(2) Check CandidatePair(('192.168.64.2', 53491) -> ('192.168.100.5', 39121)) State.WAITING -> State.IN_PROGRESS
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | DEBUG:ice:Connection(2) protocol(2) > ('192.168.100.5', 39121) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xf1d\x8am\xbe\xf4\x85\xf8\xdf-G\xbf')
web_1  | INFO:ice:Connection(2) Check CandidatePair(('192.168.64.2', 53491) -> ('192.168.100.5', 39121)) State.IN_PROGRESS -> State.FAILED
web_1  | INFO:ice:Connection(2) ICE failed
web_1  | DEBUG:ice:controlled - checking -> failed
web_1  | DEBUG:dtls:client - State.NEW -> State.CONNECTING
web_1  | DEBUG:dtls:client x DTLS handshake failed (connection error)
web_1  | DEBUG:dtls:client - State.CONNECTING -> State.FAILED
web_1  | DEBUG:ice:controlled - failed -> closed
web_1  | DEBUG:ice:Connection(2) protocol(2) connection_lost(None)

**Comment by jlaine** [comment]
Could you please paste the exchanged SDP? It looks as though both your endpoints are behind a NAT, which is the trickiest scenario.

I have just added an option in the web page for the 'server' example which allows you to instruct the browser to use Google's STUN server, could you give it a try and report back please?

**Comment by faizankarim** [comment]
SDP
Offer
v=0
o=- 1446382984604609569 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o
m=video 57090 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 123 127 122 125 107 108 109 124
c=IN IP4 192.168.100.17
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:782831213 1 udp 2122260223 192.168.100.17 57090 typ host generation 0 network-id 1
a=candidate:1613427357 1 tcp 1518280447 192.168.100.17 9 typ host tcptype active generation 0 network-id 1
a=ice-ufrag:AnKS
a=ice-pwd:2LDg967QEul0MAbHgDER1UW0
a=ice-options:trickle
a=fingerprint:sha-256 0C:9F:1D:33:AF:55:B7:B5:13:D6:04:5A:B0:31:2E:4B:E4:06:A5:8D:AD:11:88:F3:B5:59:67:C4:49:02:0B:22
a=setup:actpass
a=mid:0
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o 6735e545-aeea-4dc8-b615-882c553003d8
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 red/90000
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 1070270952 3160644109
a=ssrc:1070270952 cname:1gxsYdlQh+k/9h1R
a=ssrc:1070270952 msid:QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o 6735e545-aeea-4dc8-b615-882c553003d8
a=ssrc:1070270952 mslabel:QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o
a=ssrc:1070270952 label:6735e545-aeea-4dc8-b615-882c553003d8
a=ssrc:3160644109 cname:1gxsYdlQh+k/9h1R
a=ssrc:3160644109 msid:QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o 6735e545-aeea-4dc8-b615-882c553003d8
a=ssrc:3160644109 mslabel:QdONb2SO4YJLM2xPy358YZaomNlQpI2WSc8o
a=ssrc:3160644109 label:6735e545-aeea-4dc8-b615-882c553003d8
Answer
v=0
o=- 3754138479 3754138479 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=video 36038 UDP/TLS/RTP/SAVPF 96 97 100 101 127 122
c=IN IP4 192.168.64.2
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 3166973773 271409797
a=ssrc:3166973773 cname:{bf06fcef-7375-4c10-9836-aaa180229808}
a=ssrc:3166973773 msid:effbc0ee-f11e-4aa2-9a7b-824aa439ff0a 364f03ea-1fe1-4fcd-96bf-26507a3e172e
a=ssrc:3166973773 mslabel:effbc0ee-f11e-4aa2-9a7b-824aa439ff0a
a=ssrc:3166973773 label:364f03ea-1fe1-4fcd-96bf-26507a3e172e
a=ssrc:271409797 cname:{bf06fcef-7375-4c10-9836-aaa180229808}
a=ssrc:271409797 msid:effbc0ee-f11e-4aa2-9a7b-824aa439ff0a 364f03ea-1fe1-4fcd-96bf-26507a3e172e
a=ssrc:271409797 mslabel:effbc0ee-f11e-4aa2-9a7b-824aa439ff0a
a=ssrc:271409797 label:364f03ea-1fe1-4fcd-96bf-26507a3e172e
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:100 H264/90000
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=fmtp:100 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtcp-fb:127 goog-remb
a=fmtp:127 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=127
a=candidate:1c5d3640197e946b101fe4f5b84c33f7 1 udp 2130706431 192.168.64.2 36038 typ host
a=candidate:3dd36a31375cd08394062fcf44ee3d23 1 udp 1694498815 104.248.51.16 36038 typ srflx raddr 192.168.64.2 rport 36038
a=end-of-candidates
a=ice-ufrag:DXb2
a=ice-pwd:yRoQlXjr2DZg5ZsHMzDZqA
a=fingerprint:sha-256 B1:16:76:36:16:F9:C6:67:17:D2:EB:CE:D4:75:76:84:25:94:31:BC:11:F9:E1:97:A4:98:EA:51:A1:B4:C3:4D
a=setup:active

**Comment by faizankarim** [comment]
same not working when stun server checked.

web_1  | DEBUG:ice:controlled - new -> checking
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('192.168.100.17', 59564)) State.FROZEN -> State.WAITING
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('58.65.133.173', 36311)) State.FROZEN -> State.WAITING
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('192.168.100.17', 59564)) State.WAITING -> State.IN_PROGRESS
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('58.65.133.173', 36311)) State.WAITING -> State.IN_PROGRESS
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(0) protocol(0) > ('192.168.100.17', 37789) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'D\x1a\x90\xb8\xe8fl\xd3\xb9\xe6\x83\xdf')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('192.168.100.17', 59564) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xdd=\x16\xe9\x1f\xc0\xdb\xa1\x9e\xd3\x88;')
web_1  | DEBUG:ice:Connection(1) protocol(1) > ('58.65.133.173', 36311) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\x93/\xfe\xc9o\x96\xdd\xae\x1e\xd3i')
web_1  | INFO:ice:Connection(0) Check CandidatePair(('192.168.64.2', 48295) -> ('192.168.100.17', 37789)) State.IN_PROGRESS -> State.FAILED
web_1  | INFO:ice:Connection(0) ICE failed
web_1  | DEBUG:ice:controlled - checking -> failed
web_1  | DEBUG:dtls:client - State.NEW -> State.CONNECTING
web_1  | DEBUG:dtls:client x DTLS handshake failed (connection error)
web_1  | DEBUG:dtls:client - State.CONNECTING -> State.FAILED
web_1  | DEBUG:ice:controlled - failed -> closed
web_1  | DEBUG:ice:Connection(0) protocol(0) connection_lost(None)
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('192.168.100.17', 59564)) State.IN_PROGRESS -> State.FAILED
web_1  | INFO:ice:Connection(1) Check CandidatePair(('192.168.64.2', 49741) -> ('58.65.133.173', 36311)) State.IN_PROGRESS -> State.FAILED
web_1  | INFO:ice:Connection(1) ICE failed
web_1  | DEBUG:ice:controlled - checking -> failed
web_1  | DEBUG:dtls:client - State.NEW -> State.CONNECTING
web_1  | DEBUG:dtls:client x DTLS handshake failed (connection error)
web_1  | DEBUG:dtls:client - State.CONNECTING -> State.FAILED
web_1  | DEBUG:ice:controlled - failed -> closed
web_1  | DEBUG:ice:Connection(1) protocol(1) connection_lost(None)

**Comment by faizankarim** [comment]
sdp after stun server checked.

SDP
Offer
v=0
o=- 1969113780784124742 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F
m=video 36311 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 123 127 122 125 107 108 109 124
c=IN IP4 58.65.133.173
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:782831213 1 udp 2122260223 192.168.100.17 59564 typ host generation 0 network-id 1
a=candidate:1613427357 1 tcp 1518280447 192.168.100.17 9 typ host tcptype active generation 0 network-id 1
a=candidate:3794022910 1 udp 1686052607 58.65.133.173 36311 typ srflx raddr 192.168.100.17 rport 59564 generation 0 network-id 1
a=ice-ufrag:g+nL
a=ice-pwd:whehC+JbgSQKaIFj4FMSHGr+
a=ice-options:trickle
a=fingerprint:sha-256 50:59:27:9D:0E:2E:ED:F2:03:D4:AC:D7:42:A1:B4:AE:8A:19:D4:4B:44:4B:D7:C1:92:BE:0D:A6:39:0C:16:71
a=setup:actpass
a=mid:0
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F 9b09a41c-7ea8-4822-a2db-0b124f8424a6
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 red/90000
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 1360172708 1003743280
a=ssrc:1360172708 cname:hV3Ko5Ngt2HHXr9G
a=ssrc:1360172708 msid:ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F 9b09a41c-7ea8-4822-a2db-0b124f8424a6
a=ssrc:1360172708 mslabel:ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F
a=ssrc:1360172708 label:9b09a41c-7ea8-4822-a2db-0b124f8424a6
a=ssrc:1003743280 cname:hV3Ko5Ngt2HHXr9G
a=ssrc:1003743280 msid:ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F 9b09a41c-7ea8-4822-a2db-0b124f8424a6
a=ssrc:1003743280 mslabel:ELw3rtxWR4r6jnDDDbIj0R35g1RN1rfttL5F
a=ssrc:1003743280 label:9b09a41c-7ea8-4822-a2db-0b124f8424a6
Answer
v=0
o=- 3754139888 3754139888 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=video 49741 UDP/TLS/RTP/SAVPF 96 97 100 101 127 122
c=IN IP4 192.168.64.2
a=sendrecv
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=mid:0
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 2960271796 1108671529
a=ssrc:2960271796 cname:{5750e535-85ea-4007-9dbf-a2ac0fef2ea1}
a=ssrc:2960271796 msid:7904af48-f8b5-43fd-afcb-11983f1bf1de cf1ca774-8a0a-4240-9de3-b47441a2ed2e
a=ssrc:2960271796 mslabel:7904af48-f8b5-43fd-afcb-11983f1bf1de
a=ssrc:2960271796 label:cf1ca774-8a0a-4240-9de3-b47441a2ed2e
a=ssrc:1108671529 cname:{5750e535-85ea-4007-9dbf-a2ac0fef2ea1}
a=ssrc:1108671529 msid:7904af48-f8b5-43fd-afcb-11983f1bf1de cf1ca774-8a0a-4240-9de3-b47441a2ed2e
a=ssrc:1108671529 mslabel:7904af48-f8b5-43fd-afcb-11983f1bf1de
a=ssrc:1108671529 label:cf1ca774-8a0a-4240-9de3-b47441a2ed2e
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:100 H264/90000
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=fmtp:100 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 H264/90000
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtcp-fb:127 goog-remb
a=fmtp:127 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=127
a=candidate:1c5d3640197e946b101fe4f5b84c33f7 1 udp 2130706431 192.168.64.2 49741 typ host
a=candidate:3dd36a31375cd08394062fcf44ee3d23 1 udp 1694498815 104.248.51.16 49741 typ srflx raddr 192.168.64.2 rport 49741
a=end-of-candidates
a=ice-ufrag:I0CC
a=ice-pwd:GiP3Y3hcgeVhKx2VfriyJn
a=fingerprint:sha-256 2D:49:27:58:45:29:45:8D:BF:F2:95:14:A5:50:9A:D5:01:AD:88:FA:22:E9:E1:EA:22:DF:91:22:BF:A9:37:47
a=setup:active

**Comment by jlaine** [comment]
OK, well if it's still not working I suggest you look at your firewall on the server side, your PaaS provider most likely blocks UDP traffic unless you explicitly open it.
