### ISSUE TITLE
videostream-cli won't accept the SDP paste

### ISSUE THREAD

**Issue by joseph-long** [jlaine/aiortc#111]
I'm not sure how the reading is implemented (and not great at reading async Python yet!) but it looks like there's a maximum number of characters I can enter before hitting return, and that number is < the number of characters in the SDP offer. If I try to paste the SDP offer, it tops out at exactly 1024 characters (I tried holding down `a` to see 😄) before ringing the terminal bell. Doesn't seem to be my terminal either (iTerm on macOS, also tried Terminal.app). This is on Python 3.6 packaged by Anaconda, with aiortc==0.9.14 and the contents of the example taken from `master` for what it's worth.

**Comment by joseph-long** [comment]
Doesn't appear to happen on Linux. Guess I need to figure out what's special about input buffering in macOS. Can you point me to where the prompt for input happens in that example / aiortc?

**Comment by joseph-long** [comment]
Rats, seems to be unrelated to Python: https://superuser.com/questions/264407/macosx-10-6-7-cuts-off-stdin-at-1024-chars

**Comment by jlaine** [comment]
The signaling methods used by the examples are in `aiortc.contrib.signaling`, for instance the copy-and-paste signaling is here:

https://github.com/jlaine/aiortc/blob/fc73e2041c4161499dc6a9f644bb9e8129addf91/aiortc/contrib/signaling.py#L39

**Comment by jlaine** [comment]
From reading various documents this seems to be a well-known issue with OS X. I'm closing this issue for now, but feel free to re-open if you find a workaround.
