### ISSUE TITLE
Installation fails in mac mohave

### ISSUE THREAD

**Issue by mayursadawana** [jlaine/aiortc#117]
Hey Jeremy!
The installation is failing in mac mohave via pip, pip3, or via pycharm as well.
I'm not a developer and naive in solving these issues. 
Kindly guide.
This is the error that i am getting while installing aiortc.

`    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c build/temp.macosx-10.13-x86_64-3.7/aiortc.codecs._opus.c -o build/temp.macosx-10.13-x86_64-3.7/build/temp.macosx-10.13-x86_64-3.7/aiortc.codecs._opus.o
    build/temp.macosx-10.13-x86_64-3.7/aiortc.codecs._opus.c:493:10: fatal error: 'opus/opus.h' file not found
    #include <opus/opus.h>
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1`

**Comment by jlaine** [comment]
Hello, the error you reported means you do not have the `opus` codec installed. I suggest you follow the instructions provided in the README:

`brew install ffmpeg opus libvpx pkg-config`
