### ISSUE TITLE
Can't build the thing, requires outdated visual c++

### ISSUE THREAD

**Issue by enjoysmath** [jlaine/aiortc#124]
C:\MyProjects\___MECHANIKOS\GPUCloudDeepLearningResearch>pip install aiohttp aiortc opencv-python
Requirement already satisfied: aiohttp in c:\python36-32\lib\site-packages (3.5.4)
Collecting aiortc
  Using cached https://files.pythonhosted.org/packages/ba/ae/35360b00e9f03103bebb553c37220f721f766f90490b4203912cfadf0be2/aiortc-0.9.18.tar.gz
Collecting opencv-python
  Using cached https://files.pythonhosted.org/packages/49/4b/ad55a2e2c309fb698e1283e687129e0892c7864de9a4424c4ff01ba0a3bb/opencv_python-4.0.0.21-cp36-cp36m-win32.whl
Requirement already satisfied: chardet<4.0,>=2.0 in c:\python36-32\lib\site-packages (from aiohttp) (3.0.4)
Requirement already satisfied: typing-extensions>=3.6.5; python_version < "3.7" in c:\python36-32\lib\site-packages (from aiohttp) (3.7.2)
Requirement already satisfied: idna-ssl>=1.0; python_version < "3.7" in c:\python36-32\lib\site-packages (from aiohttp) (1.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python36-32\lib\site-packages (from aiohttp) (1.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\python36-32\lib\site-packages (from aiohttp) (3.0.1)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\python36-32\lib\site-packages (from aiohttp) (4.5.2)
Requirement already satisfied: attrs>=17.3.0 in c:\python36-32\lib\site-packages (from aiohttp) (18.2.0)
Requirement already satisfied: aioice<0.7.0,>=0.6.12 in c:\python36-32\lib\site-packages (from aiortc) (0.6.12)
Collecting av<7.0.0,>=6.1.0 (from aiortc)
  Using cached https://files.pythonhosted.org/packages/15/80/edc9e110b2896ebe16863051e68bd4786efeda71ce94b81a048d146062cc/av-6.1.0.tar.gz
Requirement already satisfied: cffi>=1.0.0 in c:\users\fruitfulapproach\appdata\roaming\python\python36\site-packages (from aiortc) (1.11.5)
Collecting crc32c (from aiortc)
Collecting cryptography>=2.2 (from aiortc)
  Using cached https://files.pythonhosted.org/packages/af/d7/9e6442de1aa61d3268e5abd7fb73b130cfc2e42439a7db42248653844593/cryptography-2.4.2-cp36-cp36m-win32.whl
Collecting pyee (from aiortc)
  Using cached https://files.pythonhosted.org/packages/8e/06/10c18578e2d8b9cf9902f424f86d433c647ca55e82293100f53e6c0afab4/pyee-5.0.0-py2.py3-none-any.whl
Collecting pylibsrtp>=0.5.6 (from aiortc)
  Using cached https://files.pythonhosted.org/packages/77/21/0a65a6ea02879fd4af7f6e137cb4fb14a64f72f8557112408462fc43124f/pylibsrtp-0.6.0-cp36-cp36m-win32.whl
Collecting pyopenssl (from aiortc)
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.11.3 in c:\python36-32\lib\site-packages (from opencv-python) (1.14.5)
Requirement already satisfied: idna>=2.0 in c:\python36-32\lib\site-packages (from idna-ssl>=1.0; python_version < "3.7"->aiohttp) (2.6)
Requirement already satisfied: netifaces in c:\python36-32\lib\site-packages (from aioice<0.7.0,>=0.6.12->aiortc) (0.10.9)
Requirement already satisfied: pycparser in c:\users\fruitfulapproach\appdata\roaming\python\python36\site-packages (from cffi>=1.0.0->aiortc) (2.19)
Collecting asn1crypto>=0.21.0 (from cryptography>=2.2->aiortc)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.4.1 in c:\python36-32\lib\site-packages (from cryptography>=2.2->aiortc) (1.11.0)
Building wheels for collected packages: aiortc, av
  Running setup.py bdist_wheel for aiortc ... error
  Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\FRUITF~1\\AppData\\Local\\Temp\\pip-install-5l34ichq\\aiortc\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\FRUITF~1\AppData\Local\Temp\pip-wheel-k1arcvoo --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\aiortc
  copying aiortc\clock.py -> build\lib.win32-3.6\aiortc
  copying aiortc\events.py -> build\lib.win32-3.6\aiortc
  copying aiortc\exceptions.py -> build\lib.win32-3.6\aiortc
  copying aiortc\jitterbuffer.py -> build\lib.win32-3.6\aiortc
  copying aiortc\mediastreams.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rate.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcconfiguration.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcdatachannel.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcdtlstransport.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcicetransport.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcpeerconnection.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcrtpparameters.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcrtpreceiver.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcrtpsender.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcrtptransceiver.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcsctptransport.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtcsessiondescription.py -> build\lib.win32-3.6\aiortc
  copying aiortc\rtp.py -> build\lib.win32-3.6\aiortc
  copying aiortc\sdp.py -> build\lib.win32-3.6\aiortc
  copying aiortc\stats.py -> build\lib.win32-3.6\aiortc
  copying aiortc\utils.py -> build\lib.win32-3.6\aiortc
  copying aiortc\__init__.py -> build\lib.win32-3.6\aiortc
  creating build\lib.win32-3.6\aiortc\codecs
  copying aiortc\codecs\g711.py -> build\lib.win32-3.6\aiortc\codecs
  copying aiortc\codecs\h264.py -> build\lib.win32-3.6\aiortc\codecs
  copying aiortc\codecs\opus.py -> build\lib.win32-3.6\aiortc\codecs
  copying aiortc\codecs\vpx.py -> build\lib.win32-3.6\aiortc\codecs
  copying aiortc\codecs\__init__.py -> build\lib.win32-3.6\aiortc\codecs
  creating build\lib.win32-3.6\aiortc\contrib
  copying aiortc\contrib\media.py -> build\lib.win32-3.6\aiortc\contrib
  copying aiortc\contrib\signaling.py -> build\lib.win32-3.6\aiortc\contrib
  copying aiortc\contrib\__init__.py -> build\lib.win32-3.6\aiortc\contrib
  running build_ext
  generating cffi module 'build\\temp.win32-3.6\\Release\\aiortc.codecs._vpx.c'
  creating build\temp.win32-3.6
  creating build\temp.win32-3.6\Release
  generating cffi module 'build\\temp.win32-3.6\\Release\\aiortc.codecs._opus.c'
  building 'aiortc.codecs._opus' extension
  creating build\temp.win32-3.6\Release\build
  creating build\temp.win32-3.6\Release\build\temp.win32-3.6
  creating build\temp.win32-3.6\Release\build\temp.win32-3.6\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python36-32\include -Ic:\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcbuild\temp.win32-3.6\Release\aiortc.codecs._opus.c /Fobuild\temp.win32-3.6\Release\build\temp.win32-3.6\Release\aiortc.codecs._opus.obj
  aiortc.codecs._opus.c
  build\temp.win32-3.6\Release\aiortc.codecs._opus.c(493): fatal error C1083: Cannot open include file: 'opus/opus.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for aiortc
  Running setup.py clean for aiortc
  Running setup.py bdist_wheel for av ... error
  Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\FRUITF~1\\AppData\\Local\\Temp\\pip-install-5l34ichq\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\FRUITF~1\AppData\Local\Temp\pip-wheel-yn9ebcj9 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\av
  copying av\datasets.py -> build\lib.win32-3.6\av
  copying av\deprecation.py -> build\lib.win32-3.6\av
  copying av\__init__.py -> build\lib.win32-3.6\av
  copying av\__main__.py -> build\lib.win32-3.6\av
  creating build\lib.win32-3.6\scratchpad
  copying scratchpad\audio.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\audio_player.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\average.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\cctx_decode.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\cctx_encode.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\decode.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\decode_threads.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\dump_format.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\encode.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\encode_frames.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\experimental.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\filmstrip.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\frame_seek_example.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\glproxy.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\graph.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\merge-filmstrip.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\player.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\qtproxy.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\remux.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\resource_use.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\save_subtitles.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\second_seek_example.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\seekmany.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\show_frames_opencv.py -> build\lib.win32-3.6\scratchpad
  copying scratchpad\__init__.py -> build\lib.win32-3.6\scratchpad
  creating build\lib.win32-3.6\av\audio
  copying av\audio\__init__.py -> build\lib.win32-3.6\av\audio
  creating build\lib.win32-3.6\av\codec
  copying av\codec\__init__.py -> build\lib.win32-3.6\av\codec
  creating build\lib.win32-3.6\av\container
  copying av\container\__init__.py -> build\lib.win32-3.6\av\container
  creating build\lib.win32-3.6\av\data
  copying av\data\__init__.py -> build\lib.win32-3.6\av\data
  creating build\lib.win32-3.6\av\filter
  copying av\filter\__init__.py -> build\lib.win32-3.6\av\filter
  creating build\lib.win32-3.6\av\subtitles
  copying av\subtitles\__init__.py -> build\lib.win32-3.6\av\subtitles
  creating build\lib.win32-3.6\av\video
  copying av\video\__init__.py -> build\lib.win32-3.6\av\video
  running build_ext
  running config
  writing build\temp.win32-3.6\Release\include\pyav\config.h
  running cythonize
  building 'av.buffer' extension
  creating build\temp.win32-3.6\Release\src
  creating build\temp.win32-3.6\Release\src\av
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Iinclude -Ic:\python36-32\include -Ibuild\temp.win32-3.6\Release\include -Ic:\python36-32\include -Ic:\python36-32\include -Ibuild\temp.win32-3.6\Release\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc\av\buffer.c /Fobuild\temp.win32-3.6\Release\src\av\buffer.obj
  buffer.c
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\python36-32\libs /LIBPATH:c:\python36-32\PCbuild\win32 /LIBPATH:c:\python36-32\libs /LIBPATH:c:\python36-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" avformat.lib avcodec.lib swresample.lib swscale.lib avdevice.lib avfilter.lib avutil.lib /EXPORT:PyInit_buffer build\temp.win32-3.6\Release\src\av\buffer.obj /OUT:build\lib.win32-3.6\av\buffer.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\src\av\buffer.cp36-win32.lib /OPT:NOREF
  LINK : fatal error LNK1181: cannot open input file 'avformat.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe' failed with exit status 1181

  ----------------------------------------
  Failed building wheel for av
  Running setup.py clean for av
Failed to build aiortc av
Installing collected packages: av, crc32c, asn1crypto, cryptography, pyee, pylibsrtp, pyopenssl, aiortc, opencv-python
  Running setup.py install for av ... error
    Complete output from command c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\FRUITF~1\\AppData\\Local\\Temp\\pip-install-5l34ichq\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\FRUITF~1\AppData\Local\Temp\pip-record-foc3l784\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\av
    copying av\datasets.py -> build\lib.win32-3.6\av
    copying av\deprecation.py -> build\lib.win32-3.6\av
    copying av\__init__.py -> build\lib.win32-3.6\av
    copying av\__main__.py -> build\lib.win32-3.6\av
    creating build\lib.win32-3.6\scratchpad
    copying scratchpad\audio.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\audio_player.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\average.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\cctx_decode.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\cctx_encode.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\decode.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\decode_threads.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\dump_format.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\encode.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\encode_frames.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\experimental.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\filmstrip.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\frame_seek_example.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\glproxy.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\graph.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\merge-filmstrip.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\player.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\qtproxy.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\remux.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\resource_use.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\save_subtitles.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\second_seek_example.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\seekmany.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\show_frames_opencv.py -> build\lib.win32-3.6\scratchpad
    copying scratchpad\__init__.py -> build\lib.win32-3.6\scratchpad
    creating build\lib.win32-3.6\av\audio
    copying av\audio\__init__.py -> build\lib.win32-3.6\av\audio
    creating build\lib.win32-3.6\av\codec
    copying av\codec\__init__.py -> build\lib.win32-3.6\av\codec
    creating build\lib.win32-3.6\av\container
    copying av\container\__init__.py -> build\lib.win32-3.6\av\container
    creating build\lib.win32-3.6\av\data
    copying av\data\__init__.py -> build\lib.win32-3.6\av\data
    creating build\lib.win32-3.6\av\filter
    copying av\filter\__init__.py -> build\lib.win32-3.6\av\filter
    creating build\lib.win32-3.6\av\subtitles
    copying av\subtitles\__init__.py -> build\lib.win32-3.6\av\subtitles
    creating build\lib.win32-3.6\av\video
    copying av\video\__init__.py -> build\lib.win32-3.6\av\video
    running build_ext
    running config
    writing build\temp.win32-3.6\Release\include\pyav\config.h
    running cythonize
    building 'av.buffer' extension
    creating build\temp.win32-3.6\Release\src
    creating build\temp.win32-3.6\Release\src\av
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Dinline=__inline -Ic:\python36-32\include -Ibuild\temp.win32-3.6\Release\include -Iinclude -Ic:\python36-32\include -Ic:\python36-32\include -Ibuild\temp.win32-3.6\Release\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsrc\av\buffer.c /Fobuild\temp.win32-3.6\Release\src\av\buffer.obj
    buffer.c
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\python36-32\PCbuild\win32 /LIBPATH:c:\python36-32\libs /LIBPATH:c:\python36-32\libs /LIBPATH:c:\python36-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" avformat.lib avfilter.lib avutil.lib swresample.lib avcodec.lib swscale.lib avdevice.lib /EXPORT:PyInit_buffer build\temp.win32-3.6\Release\src\av\buffer.obj /OUT:build\lib.win32-3.6\av\buffer.cp36-win32.pyd /IMPLIB:build\temp.win32-3.6\Release\src\av\buffer.cp36-win32.lib /OPT:NOREF
    LINK : fatal error LNK1181: cannot open input file 'avformat.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe' failed with exit status 1181

    ----------------------------------------
Command "c:\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\FRUITF~1\\AppData\\Local\\Temp\\pip-install-5l34ichq\\av\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\FRUITF~1\AppData\Local\Temp\pip-record-foc3l784\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\FRUITF~1\AppData\Local\Temp\pip-install-5l34ichq\av\

**Comment by jlaine** [comment]
Read the log carefully, this is not an error building `aiortc` but `PyAV`, please report the issue there.

**Comment by qube13** [comment]
Is there anywhere a solution to this problem?
