### ISSUE TITLE
RTX packet with empty payload causes DTLS to shutdown

### ISSUE THREAD

**Issue by zhiweny1122** [jlaine/aiortc#129]
Hi jlaine:
I opened a new issue for the dtls close issue in 2 minutes.
I never find this issue on 0.9.13 and it happened on 0.9.18.
I add the debug info in dtlstransport.py in line 480.
The error info is "FAILED unpack requires a buffer of 2 bytes"
Can you give some comments?
I pasted the log here.
"DEBUG:rtp:receiver(video) < RtpPacket(seq=45129, ts=845146785, marker=1, payload=97, 229 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54920, ts=4185232608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54921, ts=4185232608, marker=1, payload=97, 1125 bytes)
DEBUG:rtp:receiver(video) < RtcpSrPacket(ssrc=2859732783, sender_info=RtcpSenderInfo(ntp_timestamp=16136650649041527701, rtp_timestamp=845150655, packet_count=78213, octet_count=86404907), reports=[])
DEBUG:rtp:receiver(video) < RtpPacket(seq=45130, ts=845149665, marker=1, payload=97, 353 bytes)
DEBUG:rtp:receiver(video) > RtcpPsfbPacket(fmt=15, ssrc=3015268611, media_ssrc=0, fci=b'REMB\x02\x00\xaa_\xaat\x0f/\x8b\xdd;i')
DEBUG:rtp:sender(video) > RtpPacket(seq=54922, ts=4185235608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54923, ts=4185235608, marker=1, payload=97, 327 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54924, ts=4185238608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54925, ts=4185238608, marker=1, payload=97, 1006 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=45131, ts=845152905, marker=1, payload=97, 378 bytes)
DEBUG:rtp:receiver(video) > RtcpPsfbPacket(fmt=15, ssrc=3015268611, media_ssrc=0, fci=b'REMB\x02\x00\xa2u\xaat\x0f/\x8b\xdd;i')
DEBUG:rtp:sender(video) > RtpPacket(seq=54926, ts=4185241608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54927, ts=4185241608, marker=1, payload=97, 354 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=45132, ts=845158575, marker=0, payload=97, 1034 bytes)
DEBUG:rtp:receiver(video) > RtcpPsfbPacket(fmt=15, ssrc=3015268611, media_ssrc=0, fci=b'REMB\x02\x00\xb6\x0f\xaat\x0f/\x8b\xdd;i')
DEBUG:rtp:sender(video) > RtpPacket(seq=54928, ts=4185244608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) > RtpPacket(seq=54929, ts=4185244608, marker=1, payload=97, 1169 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=45133, ts=845158575, marker=0, payload=97, 1035 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=45134, ts=845158575, marker=1, payload=97, 1035 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=18620, ts=844931325, marker=1, payload=98, 404 bytes)
DEBUG:rtp:receiver(video) < RtpPacket(seq=18621, ts=845160285, marker=0, payload=98, 0 bytes)
FAILED unpack requires a buffer of 2 bytes
DEBUG:dtls:server - State.CONNECTED -> State.CLOSED
DEBUG:rtp:sender(video) > RtpPacket(seq=54930, ts=4185247608, marker=0, payload=97, 1300 bytes)
DEBUG:rtp:sender(video) - RTP finished
DEBUG:rtp:sender(video) > RtcpSrPacket(ssrc=3015268611, sender_info=RtcpSenderInfo(ntp_timestamp=16136650775727046999, rtp_timestamp=4185244608, packet_count=15038, octet_count=14827840), reports=[])
DEBUG:rtp:sender(video) > RtcpSdesPacket(chunks=[RtcpSourceInfo(ssrc=3015268611, items=[(1, b'{4359bd3b-e51f-4159-b5f0-81e0189c8501}')])])
DEBUG:ice:Connection(0) protocol(1) > ('192.168.12.46', 39400) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'L8U]\xd1\x05cT\x95\x9f\xb7i')
DEBUG:ice:Connection(0) protocol(1) < ('192.168.12.46', 39400) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'L8U]\xd1\x05cT\x95\x9f\xb7i')
DEBUG:rtp:receiver(video) > RtcpRrPacket(ssrc=3015268611, reports=[RtcpReceiverInfo(ssrc=2859732783, fraction_lost=0, packets_lost=0, highest_sequence=45134, jitter=1183, lsr=3863283890, dlsr=59173), RtcpReceiverInfo(ssrc=2346531689, fraction_lost=0, packets_lost=0, highest_sequence=18621, jitter=29019, lsr=0, dlsr=0)])
DEBUG:rtp:sender(video) > RtcpSrPacket(ssrc=3015268611, sender_info=RtcpSenderInfo(ntp_timestamp=16136650775727046999, rtp_timestamp=4185244608, packet_count=15038, octet_count=14827840), reports=[])

"

**Comment by jlaine** [comment]
Can you provide some information about the corresponding SDP please,and how I can reproduce this? What is on the other side (a browser? which?) I'd like to know what kind of codec produces RTP packets with no payload.

Throwing the packet away in the DTLS layer might not be the right solution, as it will mess up a number of counters. Also, please note that `aiortc` has 100% test coverage so any PR needs an associated test case.

**Comment by jlaine** [comment]
OK I thought so. Could you please send me the raw packet *before* it gets parsed? The best would be to add some code at the start of `RTCDtlsTransport._handle_rtp_data`:

```
with open('rtp.bin', 'wb') as fp:
    fp.write(data)
```

Let the code fail, so the last capture RTP packet should be the one we want.

We need to determine whether Chrome is violating spec, or whether there is another problem in aiortc's RTP parser.
We need to determine

**Comment by jlaine** [comment]
NOTE: I found this line of code in webrtc.org:

https://chromium.googlesource.com/external/webrtc/+/cd6ae6652f075d9699c9f22795d15742ce1a7205/webrtc/video/rtp_stream_receiver.cc#390

**Comment by zhiweny1122** [comment]
Hi jlaine:
There is no "data" in RTCDtlsTransport._handle_rtp_data .
should I save packet.payload ?

**Comment by zhiweny1122** [comment]
Hi jlaine:
I pasted the log which have the SDP info.
Hope it is helpful.

"test@ubuntu:~/zhiweny/newrtc/examples/apprtc$ python apprtc.py 11114427 -v
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:websockets.protocol:client - state = CONNECTING
DEBUG:websockets.protocol:client - event = connection_made(<asyncio.sslproto._SSLProtocolTransport object at 0x7f28d217ebe0>)
DEBUG:websockets.protocol:client - state = OPEN
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=1, data=b'{"clientid": "83087483", "cmd": "register", "roomid": "11114427"}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=11 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) connection_made(<_SelectorDatagramTransport fd=12 read=idle write=<idle, bufsize=0>>)
DEBUG:ice:Connection(0) protocol(1) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'N\xa6\xae/\x95\x82\xd6\xde\xbe\x9e\xc6\x01')
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x93\xc7\xad\x8a\x98\xf1l\xc4r\xde\x18`')
DEBUG:ice:Connection(0) protocol(1) < ('74.125.204.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'N\xa6\xae/\x95\x82\xd6\xde\xbe\x9e\xc6\x01')
DEBUG:ice:Connection(0) protocol(0) < ('74.125.204.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x93\xc7\xad\x8a\x98\xf1l\xc4r\xde\x18`')
> {"sdp": "v=0\r\no=- 3757138340 3757138340 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\nm=video 51850 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\r\nc=IN IP4 10.0.2.16\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:381a04e2-ecd8-4161-a04d-ba992d4100a5 0301991c-976e-47e5-ab56-57d6609e4024\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 2660525134 3122367001\r\na=ssrc:2660525134 cname:{bb494a8b-e337-4a12-8eb6-d2e40565c7f3}\r\na=ssrc:3122367001 cname:{bb494a8b-e337-4a12-8eb6-d2e40565c7f3}\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:02d59f24398279a1bc74956f570ca74b 1 udp 2130706431 10.0.2.16 51850 typ host\r\na=candidate:5e70c409ad0bd7762e565b442cd686cb 1 udp 2130706431 192.168.12.45 39053 typ host\r\na=candidate:b37efe93c5eb0809569a59c1826668c4 1 udp 1694498815 114.242.248.48 15673 typ srflx raddr 192.168.12.45 rport 39053\r\na=candidate:bd321e59cbe176b5eceaaf6879b9f9dc 1 udp 1694498815 114.242.248.48 15674 typ srflx raddr 10.0.2.16 rport 51850\r\na=end-of-candidates\r\na=ice-ufrag:3dAI\r\na=ice-pwd:DkV5fZYXzGmkITYL5mfY2f\r\na=fingerprint:sha-256 AF:C1:86:93:5A:F1:9A:B9:0F:5A:DB:0A:6D:43:82:3B:21:72:98:14:64:BC:49:84:BE:40:F0:02:FF:2E:A8:16\r\na=setup:actpass\r\n", "type": "offer"}
Please point a browser at http://www.guoxin.cn:8888/r/11114427
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=1, data=b'{"msg":"{\\"sdp\\":\\"v=0\\\\r\\\\no=- 8061620977471369667 2 IN IP4 127.0.0.1\\\\r\\\\ns=-\\\\r\\\\nt=0 0\\\\r\\\\na=group:BUNDLE 0\\\\r\\\\na=msid-semantic: WMS JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\\\\r\\\\nm=video 9 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\\\\r\\\\nc=IN IP4 0.0.0.0\\\\r\\\\na=rtcp:9 IN IP4 0.0.0.0\\\\r\\\\na=ice-ufrag:2tjM\\\\r\\\\na=ice-pwd:M6cMBdNZ6jxQez+M1QGuNnSa\\\\r\\\\na=ice-options:trickle\\\\r\\\\na=fingerprint:sha-256 49:65:E5:17:3C:50:7C:A5:4A:F8:AE:B4:E0:F4:32:CF:7E:AA:9F:4D:2A:4F:50:70:11:FE:A2:D7:F1:55:25:DF\\\\r\\\\na=setup:active\\\\r\\\\na=mid:0\\\\r\\\\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\\\\r\\\\na=sendrecv\\\\r\\\\na=rtcp-mux\\\\r\\\\na=rtpmap:97 VP8/90000\\\\r\\\\na=rtcp-fb:97 goog-remb\\\\r\\\\na=rtcp-fb:97 nack\\\\r\\\\na=rtcp-fb:97 nack pli\\\\r\\\\na=rtpmap:98 rtx/90000\\\\r\\\\na=fmtp:98 apt=97\\\\r\\\\na=rtpmap:99 H264/90000\\\\r\\\\na=rtcp-fb:99 goog-remb\\\\r\\\\na=rtcp-fb:99 nack\\\\r\\\\na=rtcp-fb:99 nack pli\\\\r\\\\na=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\\\\r\\\\na=rtpmap:100 rtx/90000\\\\r\\\\na=fmtp:100 apt=99\\\\r\\\\na=rtpmap:101 H264/90000\\\\r\\\\na=rtcp-fb:101 goog-remb\\\\r\\\\na=rtcp-fb:101 nack\\\\r\\\\na=rtcp-fb:101 nack pli\\\\r\\\\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\\\\r\\\\na=rtpmap:102 rtx/90000\\\\r\\\\na=fmtp:102 apt=101\\\\r\\\\na=ssrc-group:FID 1273892973 4229671452\\\\r\\\\na=ssrc:1273892973 cname:rY8sfNX5I3n+kRBk\\\\r\\\\na=ssrc:1273892973 msid:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH 5e901bc8-8030-48d9-8480-ffcf12bf1d9c\\\\r\\\\na=ssrc:1273892973 mslabel:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\\\\r\\\\na=ssrc:1273892973 label:5e901bc8-8030-48d9-8480-ffcf12bf1d9c\\\\r\\\\na=ssrc:4229671452 cname:rY8sfNX5I3n+kRBk\\\\r\\\\na=ssrc:4229671452 msid:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH 5e901bc8-8030-48d9-8480-ffcf12bf1d9c\\\\r\\\\na=ssrc:4229671452 mslabel:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\\\\r\\\\na=ssrc:4229671452 label:5e901bc8-8030-48d9-8480-ffcf12bf1d9c\\\\r\\\\n\\",\\"type\\":\\"answer\\"}","error":""}\n', rsv1=False, rsv2=False, rsv3=False)
< {"sdp":"v=0\r\no=- 8061620977471369667 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\r\nm=video 9 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:2tjM\r\na=ice-pwd:M6cMBdNZ6jxQez+M1QGuNnSa\r\na=ice-options:trickle\r\na=fingerprint:sha-256 49:65:E5:17:3C:50:7C:A5:4A:F8:AE:B4:E0:F4:32:CF:7E:AA:9F:4D:2A:4F:50:70:11:FE:A2:D7:F1:55:25:DF\r\na=setup:active\r\na=mid:0\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 goog-remb\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 goog-remb\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=ssrc-group:FID 1273892973 4229671452\r\na=ssrc:1273892973 cname:rY8sfNX5I3n+kRBk\r\na=ssrc:1273892973 msid:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH 5e901bc8-8030-48d9-8480-ffcf12bf1d9c\r\na=ssrc:1273892973 mslabel:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\r\na=ssrc:1273892973 label:5e901bc8-8030-48d9-8480-ffcf12bf1d9c\r\na=ssrc:4229671452 cname:rY8sfNX5I3n+kRBk\r\na=ssrc:4229671452 msid:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH 5e901bc8-8030-48d9-8480-ffcf12bf1d9c\r\na=ssrc:4229671452 mslabel:JCPaEdPamZxOzdW929TtdzDMejnKiAgCnjcH\r\na=ssrc:4229671452 label:5e901bc8-8030-48d9-8480-ffcf12bf1d9c\r\n","type":"answer"}
Track video received
DEBUG:ice:controlling - new -> checking
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=1, data=b'{"msg":"{\\"type\\":\\"candidate\\",\\"label\\":0,\\"id\\":\\"0\\",\\"candidate\\":\\"candidate:833681328 1 udp 2122260223 192.168.12.46 53116 typ host generation 0 ufrag 2tjM network-id 1\\"}","error":""}\n', rsv1=False, rsv2=False, rsv3=False)
< {"type":"candidate","label":0,"id":"0","candidate":"candidate:833681328 1 udp 2122260223 192.168.12.46 53116 typ host generation 0 ufrag 2tjM network-id 1"}
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=1, data=b'{"msg":"{\\"type\\":\\"candidate\\",\\"label\\":0,\\"id\\":\\"0\\",\\"candidate\\":\\"candidate:3513675092 1 udp 2122194687 192.168.1.136 56347 typ host generation 0 ufrag 2tjM network-id 2 network-cost 10\\"}","error":""}\n', rsv1=False, rsv2=False, rsv3=False)
< {"type":"candidate","label":0,"id":"0","candidate":"candidate:3513675092 1 udp 2122194687 192.168.1.136 56347 typ host generation 0 ufrag 2tjM network-id 2 network-cost 10"}
INFO:ice:Connection(0) Check CandidatePair(('10.0.2.16', 51850) -> ('192.168.12.46', 53116)) State.FROZEN -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(0) > ('192.168.12.46', 53116) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'S\xa4\xb35oH\x18\xbc0$\x8f\n')
INFO:ice:Connection(0) Check CandidatePair(('192.168.12.45', 39053) -> ('192.168.12.46', 53116)) State.FROZEN -> State.IN_PROGRESS
DEBUG:ice:Connection(0) protocol(1) > ('192.168.12.46', 53116) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'9\x8d\x86\xfa\xfb3E\xbb\xf7\x02.\xa2')
DEBUG:ice:Connection(0) protocol(1) < ('192.168.12.46', 53116) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'9\x8d\x86\xfa\xfb3E\xbb\xf7\x02.\xa2')
INFO:ice:Connection(0) Check CandidatePair(('192.168.12.45', 39053) -> ('192.168.12.46', 53116)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) Check CandidatePair(('10.0.2.16', 51850) -> ('192.168.1.136', 56347)) State.FROZEN -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('192.168.12.45', 39053) -> ('192.168.1.136', 56347)) State.FROZEN -> State.FAILED
INFO:ice:Connection(0) ICE completed
DEBUG:ice:Connection(0) protocol(1) < ('192.168.12.46', 53116) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'3oMEhCnRLRbO')
DEBUG:ice:Connection(0) protocol(1) > ('192.168.12.46', 53116) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'3oMEhCnRLRbO')
DEBUG:ice:controlling - checking -> completed
DEBUG:dtls:server - State.NEW -> State.CONNECTING
DEBUG:dtls:server - DTLS handshake complete
DEBUG:dtls:server - State.CONNECTING -> State.CONNECTED
DEBUG:rtp:sender(video) - RTP started
DEBUG:rtp:sender(video) - RTCP started
DEBUG:rtp:receiver(video) - RTCP started
"

**Comment by jlaine** [comment]
There most definitely is `data` in `RTCDtlsTransport._handle_rtp_data`, it's the first argument of this function:

https://github.com/jlaine/aiortc/blob/15716eed97d953c78450f6babf719dd4cf56c210/aiortc/rtcdtlstransport.py#L512

I really need this raw data, not the parsed RTP packet as I want to ensure it's parsed correctly.

**Comment by zhiweny1122** [comment]
Hi jlaine:
I opened a new issue and upload the rtp data file.
Can you take a look at it ?
Hope it is helpful.
