### ISSUE TITLE
Pass STUN and TURN

### ISSUE THREAD

**Issue by nickaknudson** [jlaine/aiortc#13]
I want to be able to pass STUN and TURN servers down to ICE Connection.

Happy to implement, would just like to understand your preference for the implementation. Should I pass to contructor of RPC Peer Connection or as some sort of configuration on that object? 

Thanks.

**Comment by jlaine** [comment]
Hi Nick, you're right I haven't exposed these options in the PeerConnection constructor. The underlying ICE implementation (aioice) supports a single STUN server and/or a single TURN server so it's a question of wiring it up.

**Comment by jlaine** [comment]
In terms of API I'm kind of torn. So far I have very closely tracked the WebRTC / ORTC APIs, but the RTCConfiguration.iceServers seems pretty cumbersome.

**Comment by galindro** [comment]
I need this too
