### ISSUE TITLE
Server example: ICE connection failed

### ISSUE THREAD

**Issue by hendl** [jlaine/aiortc#131]
Everytime I try to set up the server example the ICE connection fails.

I already tryed to use a stun and a turn server but the result is the same:
`config.iceServers = [
    {
      'urls': 'stun:stun.l.google.com:19302?transport=tcp'
    },
    {
      'urls': 'turn:numb.viagenie.ca',
      'credential': 'muazkh',
      'username': 'webrtc@live.com'
    }
  ];`

Is there a way to configure the server to use a stun server because it always responds with its internal IP:
`a=candidate:9333c84bcc1b0bf56713df9036e6b4d9 1 udp 2130706431 172.17.0.2 53159 typ host
`

Thx in advance 
hendl

**Comment by jlaine** [comment]
Could you send both the SDP sent by the browser and by the server please?

**Comment by jlaine** [comment]
The offer looks fine, it contains an `srflx` candidate, which was discovered using STUN.

The answer on the other hand doesn't have such a candidate. If you run the *unmodified* server example it should already use Google's STUN server, so I'd expect an `srflx` candidate, unless your network setup / firewall is blocking it.

If you run the server in verbose mode (`python examples/server/server.py -v`) you should see something like:

```
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\x89\xbf\x03\xf2\x90/$4\xe4\xc7\xf8\x88')
DEBUG:ice:Connection(0) protocol(0) < ('74.125.143.127', 19302) Message(message_method=Method.BINDING, message_class=Class.RESPONSE, transaction_id=b'\x89\xbf\x03\xf2\x90/$4\xe4\xc7\xf8\x88')
```

**Comment by hendl** [comment]
Hmm ok good to know.
The server seems to try to connect to the google stun STUN server.
```
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class$Class.REQUEST, transaction_id=b':\xa7\xc8v!\x810\x00\x9e\xa6K&')
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=
Class.REQUEST, transaction_id=b':\xa7\xc8v!\x810\x00\x9e\xa6K&')
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=
Class.REQUEST, transaction_id=b':\xa7\xc8v!\x810\x00\x9e\xa6K&')
DEBUG:ice:Connection(0) protocol(0) > ('stun.l.google.com', 19302) Message(message_method=Method.BINDING, message_class=
Class.REQUEST, transaction_id=b':\xa7\xc8v!\x810\x00\x9e\xa6K&')
```

Unfortunately I am not able to change the firewall rules if the requests are blocked.
Is there a way to configure the server, that he uses TCP requests?
Or would be it be a better approach if I install a own STUN server in the network?

**Comment by jlaine** [comment]
If the problem is specifically accessing Google's STUN server, you can specify another one in the RTCPeerConnection constructor:

```python
from aiortc import RTCConfiguration, RTCIceServer
pc = RTCPeerConnection(RTCConfiguration(
    iceServers=[RTCIceServer(
        urls=['stun:some.example.com'])]))
```

If the problem is more broadly "the server cannot receive UDP", I'd suggest revisiting your hosting options, this is a very restrictive setup.

**Comment by hendl** [comment]
Thx for your quick and helpful responses.
 
Yeah its kinda complicated. We need the server for an university project and the admins probably wont allow outgoing UDP connections. 

If we set up our own TURN server in the same network and allow an connection from outside, would this solve the problem? Or is there a possibility to specifiy a TCP STUN server at the server?
I already tried to use the same configuration as in the client to set the connection to TCP but I get a python exception.
`pc = RTCPeerConnection(RTCConfiguration(iceServers=[RTCIceServer(urls=['stun:stun.l.google.com:19302?transport=tcp'])]))`


```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/aiortc/examples/server/server.py", line 114, in offer
    await pc.setRemoteDescription(offer)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 660, in setRemoteDescription
    transceiver = self.__createTransceiver(direction='recvonly', kind=media.kind)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 834, in __createTransceiver
    dtlsTransport = self.__createDtlsTransport()
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 812, in __createDtlsTransport
    iceGatherer = RTCIceGatherer(iceServers=self.__configuration.iceServers)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcicetransport.py", line 146, in __init__
    ice_kwargs = connection_kwargs(iceServers)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcicetransport.py", line 73, in connection_kwargs
    parsed = parse_stun_turn_uri(uri)
  File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcicetransport.py", line 114, in parse_stun_turn_uri
    raise ValueError('malformed uri')
ValueError: malformed uri
```

**Comment by jlaine** [comment]
STUN over TCP isn't supported by `aioice`
