### ISSUE TITLE
Play received video track on RPi

### ISSUE THREAD

**Issue by Duriqs** [jlaine/aiortc#132]
Hello! I am quite new to your library and to RPi too. Nevertheless...I use your library to make app which sends data from PC browser to RPi, which should play recieved data. I was trying to display  recieved video track via OpenCV (both as individual frames and video file), but I couldn´t get it work. I was thinking about using omxplayer as it can be launched without GUI, but I am not sure about it... I would like to know what is Type of recieved tracks - I couldn´t find sufficient documentation, so I thought maybe you could help me :)

**Comment by jlaine** [comment]
aiortc doesn't handle any kind of GUI, what you do with the media is really outside the scope of the project.

This may sound dumb but if you need a GUI why not just use a browser?

**Comment by Duriqs** [comment]
I know it is outside the scope of project... I was just wondering what is the type of recieved track - if you preserve all attributes or just some of them and how to access them (if jsut like track.kind and so on...)

In my case browser is not the best solution, as I want solution which is as lightweight as possible - just to run my program on startup, with disabled GUI and when a stream comes, just play it fullscreen.

**Comment by jlaine** [comment]
The "track" gives you both the kind, and a method to receive the audio / video frames as they arrive, for whatever processing you require. You mentioned you tried to display these frames but it didn't work - do you have some code to show?

Also, I'm not sure I understand what you mean with a "disabled GUI", you will almost certainly need an X11 session to be able to display any kind of images.

**Comment by Duriqs** [comment]
OK...to make a long story short - I changed you server example - I´ve put 2 lines to VideoTransformTrack class - in case no transform is done, an image should be displayed on Pi

```javascript     
else:
   img = np.asarray(frame)
   cv2.imshow('frame', img)
   return frame
```
The first line was added after TypeError I got when tried only to show frame with cv2. But neither converting with np did not help. Nothing is displayed on Pi and I also won´t recieve image back to the browser - so there is some problem with processing. So that´s why I´ve asked about "track" type - to understand how to process it...
In ideal case, I would try to process it with some library which can directly write into the framebuffer - so I can avoid X11 processes...cv2 is just quick example of my problem...
Maybe you are right about efficiency of my code, but I really want to avoid a solution with browser...I know that what I need is possible - I could use uv4l which can do it, but as I need some other functionality, I am trying to build my own solution.

**Comment by Duriqs** [comment]
After some other TypeErrors I came to the solution when I got image back to the browser. There was need of further conversions (ndarray...) Even cv2 opened a new window on Pi. But window was empty - I probably need to adjust format of image...

**Comment by jlaine** [comment]
Please paste a more complete piece of code, `img = np.asarray(frame)` cannot possibly work. If you want to convert a PyAV `VideoFrame` to a numpy array, you want `frame.to_ndarray(format='bgr24')`:

https://docs.mikeboers.com/pyav/develop/api/video.html#av.video.frame.VideoFrame.to_ndarray

As for why you don't see anything, the docs clearly state you *need* `cv2.waitKey(0)`:

https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_image_display/py_image_display.html#display-an-image

Adding this gets you a single frame on screen, however it totally screws up the asyncio event loop and ends up hanging - not surprising.

It feels like you are approaching this from the wrong angle, and are in over your head. Before going further down this road I suggest you try something simpler like using a browser on the RPi side.

**Comment by Duriqs** [comment]
Ok. Thank you for help - I really appreciate it! I have one more question. When I stream video in HD resolution - with your server example - the delay is pretty bad (10+ seconds). I just recieve frames and send them back. Is there any way how to reduce the delay?

**Comment by jlaine** [comment]
Yes:
- drop frames
- reduce resolution
- use bigger hardware

Encoding an HD stream using VP8 is CPU intensive.

**Comment by Duriqs** [comment]
OK. Thank you!
