### ISSUE TITLE
AppRTC sample hanging on browser side

### ISSUE THREAD

**Issue by s0ckz** [jlaine/aiortc#133]
When I run the apprtc.py sample, the shown video at apprtc.io using Chrome eventually hangs. Sometimes it starts already stuck and sometimes it stops to play in seconds.

What kind of information do you need?

I'm testing apprtc.py and the site using the same host, also:
Chrome Version 69.0.3497.92 (Official Build) (64-bit)
Python 3 and dependencies from distribution
Ubuntu 18.04 LTS

**Comment by jlaine** [comment]
Please provide some debug output, I have absolutely nothing to go on here.

Make sure you are running the latest code from git and run:

`python examples/apprtc/apprtc.py -v`

**Comment by s0ckz** [comment]
https://pastebin.com/DHUNEWcL <= here's the debug output.

 Thanks for the rapid answer

**Comment by s0ckz** [comment]
It keep sending, but the video stops at the Chrome window.

**Comment by jlaine** [comment]
The log you sent shows that the RTP sender is exiting ("RTP finished" at line 948) and, quite logically it doesn't send anything else after that.

The RTP sender stops under one of three conditions:

- it was explicitly shutdown (CancelledError)
- the underlying DTLS transport was closed (ConnectionError)
- the track you are sending has finished (MediaStreamError)

You can tinker around with this line to determine which it is:

https://github.com/jlaine/aiortc/blob/9faa2807a821efdaee4c7fe9c84379af8657e2fa/aiortc/rtcrtpsender.py#L289

Could you share the exact command line you are using when invoking the apprtc example?

**Comment by s0ckz** [comment]
I use:
```bash
python3 -v --play-from=SampleVideo_1280x720_1mb.mp4
```
It also occurs using the sample JPEG

**Comment by jlaine** [comment]
I'm guessing the log you posted was using the MP4 file and the file simply ended!

If you specify no additional arguments, this should not occur as the track has no "end". If that is not the case please post another log as it's most probably not the same issue.

**Comment by s0ckz** [comment]
Oh gosh, that's correct. Now I'm not having issues with the other sample also. Maybe it was solved in the master branch?

You can close the issue now. Sorry !

**Comment by jlaine** [comment]
Thanks for confirming, I'll close this issue. There were indeed a couple of fixes which went in recently.
