### ISSUE TITLE
kurento: ICE connection state stuck at "checking"

### ISSUE THREAD

**Issue by howardkyu** [jlaine/aiortc#134]
I'm currently using the Python client to handle an SDP offer from a media server. On the client side, I did the following to exchange SDP offer/answers: `pc.setRemoteDescription(offer)` and `pc.setLocalDescription(await pc.createAnswer())`.

On the server side, I'm enabling trickle ICE by sending messages containing ice candidates. On the client side I converted the candidate string into an `RTCIceCandidate` and called `pc.addIceCandidate(candidate)`. However, the peer client is stuck at the "checking" state and it doesn't seem to be changing. Any ideas?

Edit: Just tried with with traditional ICE as well. If I'm understanding if candidates are included in the SDP offer, then `pc.setRemoteDescription(offer)` will automatically connect?

**Comment by jlaine** [comment]
Please paste some actual code, including an example of the candidates received using trickle ICE and how you convert them to `RTCIceCandidate`.

**Comment by howardkyu** [comment]
I'm going with the traditional ICE route for now as it is simpler for me but still causing the state to be in checking. This is the SDP offer containing the candidates from the media server. 
```
v=0
o=- 3757190350 3757190350 IN IP4 0.0.0.0
s=Kurento Media Server
t=0 0
a=group:BUNDLE audio0 video0
m=audio 19388 RTP/SAVPF 96 0
c=IN IP4 172.17.0.2
a=setup:actpass
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:96 opus/48000/2
a=rtcp:19388 IN IP4 172.17.0.2
a=rtcp-mux
a=sendrecv
a=mid:audio0
a=ssrc:1007770314 cname:user3062350444@host-5b3715df
a=ice-ufrag:mDlI
a=ice-pwd:JyEOmpeGk+VvXNZ8lOq+mj
a=fingerprint:sha-256 12:19:98:BF:EB:90:02:FC:8C:73:48:E6:F7:47:3B:98:9E:64:51:91:28:10:9F:1F:BB:57:30:56:20:4F:FC:44
a=candidate:1 1 UDP 2013266431 172.17.0.2 29399 typ host
a=candidate:2 1 TCP 1019216127 172.17.0.2 9 typ host tcptype active
a=candidate:3 1 TCP 1015021823 172.17.0.2 19388 typ host tcptype passive
a=candidate:1 2 UDP 2013266430 172.17.0.2 58378 typ host
a=candidate:2 2 TCP 1019216126 172.17.0.2 9 typ host tcptype active
a=candidate:3 2 TCP 1015021822 172.17.0.2 30605 typ host tcptype passive
m=video 19388 RTP/SAVPF 100 101
c=IN IP4 172.17.0.2
b=AS:500
a=setup:actpass
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=rtpmap:100 VP8/90000
a=rtpmap:101 H264/90000
a=rtcp:19388 IN IP4 172.17.0.2
a=rtcp-mux
a=sendrecv
a=mid:video0
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 ccm fir
a=ssrc:3546652617 cname:user3062350444@host-5b3715df
a=ice-ufrag:mDlI
a=ice-pwd:JyEOmpeGk+VvXNZ8lOq+mj
a=fingerprint:sha-256 12:19:98:BF:EB:90:02:FC:8C:73:48:E6:F7:47:3B:98:9E:64:51:91:28:10:9F:1F:BB:57:30:56:20:4F:FC:44
a=candidate:1 1 UDP 2013266431 172.17.0.2 29399 typ host
a=candidate:2 1 TCP 1019216127 172.17.0.2 9 typ host tcptype active
a=candidate:3 1 TCP 1015021823 172.17.0.2 19388 typ host tcptype passive
a=candidate:1 2 UDP 2013266430 172.17.0.2 58378 typ host
a=candidate:2 2 TCP 1019216126 172.17.0.2 9 typ host tcptype active
a=candidate:3 2 TCP 1015021822 172.17.0.2 30605 typ host tcptype passive
```

I use following code to transform it into `RTCSessionDescription` and set the `remoteDescription`:
```
async def handle(sdp_str, type):
    sdp_string = json.dumps({
        'sdp': sdp_str,
        'type': type
    })
    await pc.setRemoteDescription(offer)
    await pc.setLocalDescription(await pc.createAnswer())
    return pc.localDescription
```

**Comment by howardkyu** [comment]
Sorry I wasn't being clear. Seems like I accidentally deleted a line when I was formatting. I've updated the previous post with more context and updated code. 

At this point, I'm not using ICE trickle so I can reduce the complexity of session management. However, I'm still getting the problem where the connection is stuck in `checking`.

**Comment by jlaine** [comment]
The Python code looks odd, you are firing up an event loop inside your request handler and I'm not convinced it stays alive after the request handler completes. Your asyncio event loop needs to keep running, and your `pc` object needs to be kept alive otherwise nothing is going to happen.

I suggest you switch to a framework that is actually async, such as `aiohttp` for instance. You can look at the `server` example as a starting point.

**Comment by howardkyu** [comment]
Thanks. That seems to be what I need. I'll make some changes and see if it works.

**Comment by jlaine** [comment]
Please let me know if you make progress, I haven't had a chance to interop with Kurento and would love to know the results. So far I've run `aiortc` facing Chrome / Firefox (audio + video) and Asterisk (audio only so far)

**Comment by howardkyu** [comment]
Just an update. I changed the framework to `aiohttp` and based it off your `server` example, and it is working seamlessly. Using the simple Kurento client I used above, the Python server is able to handle multiple connections between it and the media server. Thanks for the help!

**Comment by jlaine** [comment]
That's awesome! Would you consider contributing a full example in a PR?

**Comment by howardkyu** [comment]
Sure I'd be happy too! I'll try it organize it into a nice example and submit it sometime in the near future.
