### ISSUE TITLE
rtp(rtx) empty packet

### ISSUE THREAD

**Issue by zhiweny1122** [jlaine/aiortc#135]
Hi jlaine:
I upload the rpt.bin which inlcude the rtp packet that you required in issue #129.
Please take a look at this and give your comment.
[rtpbin.zip](https://github.com/jlaine/aiortc/files/2785234/rtpbin.zip)

**Comment by jlaine** [comment]
Thanks, I can confirm the packet contains only padding, no payload. `aiortc`'s RTP parser seems to be working fine.
