### ISSUE TITLE
h.264 video

### ISSUE THREAD

**Issue by petergerten** [jlaine/aiortc#14]
great project!

I wonder what would be required to also support H.264?

**Comment by jlaine** [comment]
We would need bindings to an h.264 codec, probably ffmpeg's libavcodec.

This comes in two parts:

- cffi interface to the library's C code (see src/build_vpx.py for example)

- Python code to handle frames and pass them to the codec (see aiortc/codecs/vpx.py for example)

**Comment by petergerten** [comment]
Thanks. I will take a look at vpx.py.
Would it be possible to just use the encoded frames? I intend to re purpose them without decoding.

**Comment by jlaine** [comment]
Grabbing endoded frames sounds like a legitimate usecase buy doesn't sound h.264 specific. Do you have any comparable APIs we can draw inspiration from?

**Comment by notedit** [comment]
May be we can use pyav   https://github.com/mikeboers/PyAV

**Comment by jlaine** [comment]
Initial support for H.264 has landed in `master` thanks to @dsvictor94. We'll be refining it, but I'd already like to point out the great work done by Victor. This is the best way to get your favorite feature into `aiortc` : write the code and the corresponding tests and I'll be happy to review it!
