### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dsvictor94** [jlaine/aiortc#17]
Hi,
In a long running a did some memory test and not a leak

![aiortc_memory_leak](https://user-images.githubusercontent.com/5621021/40155043-ee4d0582-5967-11e8-9150-dc1878da9eee.png)

any tip where it can be?

**Comment by dsvictor94** [comment]
I reexecute without debug and the sabe leak was detected

![figure_1](https://user-images.githubusercontent.com/5621021/40156055-83378a1e-596d-11e8-8ea0-60fbf1c5c2bf.png)

**Comment by dsvictor94** [comment]
I investigate the object graph to locate the leak and found that it is because that queue is keeping 
hundreds of thousands of canceled Futures in that [queue](https://github.com/jlaine/aioice/blob/5b6458c7e5e827179c4dfbe836a4aded8afa401a/aioice/ice.py#L129)

In my execution that queue keep about 50 pending/complete Futures and 90000 canceled Futures

I produce a graph dependency with 3 of them 
[outfile.pdf](https://github.com/jlaine/aiortc/files/2011790/outfile.pdf)

**Comment by dsvictor94** [comment]
I continued the investigation and note it is a bug releted to python async queue: https://bugs.python.org/issue31620
I rerun the aplication with python 3.6 and no leak was detected

![figure_1-1](https://user-images.githubusercontent.com/5621021/40187154-3b24eb9e-59cd-11e8-82dc-93541a4ba2f0.png)

feel free to close this issues, and thanks to the good job with this lib!

**Comment by jlaine** [comment]
That's really interesting, thanks for investigating this!

The piece of code that generates the cancelled futures is undoubtedly here:
