### ISSUE TITLE
How to add and send ICE candidates

### ISSUE THREAD

**Issue by CharlieHollow** [jlaine/aiortc#18]
I'm writing a RTCPeerClient using aiortc to communicate with remote peer in a browser (similiar situation to apprtc.py example), but in that example, to add remote ICE candidate, it uses a peer client method called "AddIceCandidate", which does not appear in aiortc API nor exists when I build the code. 

So, how could I manage ICE candidates (remote and local) and add them to the peer?

Thanks

**Comment by jlaine** [comment]
I suggest you take a look at the provided examplea. The methods you want are createOffer (or createAnswer) and setRemoteDescription.

addIceCandidate is for ICE trickle (adding further ICE candidates after the initial offer), which aiortc doesn't currently support.

**Comment by CharlieHollow** [comment]
Those methods (createOffer and so on) I'm already using them to create a datachannel between remote peer in browser and aiortc peer. But, despite both peers have shared offer and answer info, datachannel does not work. It is still close. 

And I think maybe browser peer needs iceCandidate info.

**Comment by jlaine** [comment]
Can you please try the "server" example provided with aiortc, it illustrates how to set up a datachannel and/or media streams with a browser? It should give you a good starting point

**Comment by CharlieHollow** [comment]
Thank you so much, my bad. I did not see that example before. I'll try to use that example as reference
