### ISSUE TITLE
How can I save audio tracks sent by each client into a wave file?

### ISSUE THREAD

**Issue by sogand145** [jlaine/aiortc#19]
Hi jlaine, 
Thank you so much for writing this useful module.
Would you please let me know how to save audio tracks sent by each client into a wave file separately and then load those wave files for each other.
on the other hand, I tried to load live audio tracks for one client (instead of saving it to another format), but it played with delay and was not clear. Please tell me how can I fix it?
I appreciate for your help

**Comment by jlaine** [comment]
I have updated the "server" example to illustrate how to save received audio to a WAV file.

As for the second question, it sounds as though you're trying to do a multi-party conference, which is a non-trivial subject. This will be up to you to research and implement.

**Comment by sogand145** [comment]
Thanks a lot :)
