### ISSUE TITLE
ICE Connection State stuck at "new"

### ISSUE THREAD

**Issue by CharlieHollow** [jlaine/aiortc#22]
Hi there,

I'm trying to connect with remote peer in browser, but despite both peer exchange their answer/offer, aiortc peer ice candidate status is stuck at "new".

I've checked gathering status, and its at "complete", and signaling status is at "stable".
In addition, browser peer ice candidate status is stuck at "checking". I've tried to find out the reason why it does not work, and it could be a STUN/TURN servers problem. 

I've checked browser STUN/TURN servers and they are ok. Any idea which could be the issue?

Thanks.

EDIT: I've been checking STUN and TURN working servers, and I've even added a turn server into "rtcicetransport.py" to discard any NAT problems during signaling.

However, there is no changes. Browser peer is on Google Chrome 66.0.3359.181 (Build oficial), using javascript RTCPeerConnection, which get connected with aiortc peer using websockets. 

Browser peer get stuck on: "ICE Candidate State: checking" and "ICE Gathering State: complete", and aiortc peer get stuck on: "ICE Candidate State: new" and "ICE Gathering State: complete".

I've been dealing with this problem several days, but I dont achieve any solution. Could you help me please? 

Thanks again.

**Comment by CharlieHollow** [comment]
Finally, I've found out the problem. AioRTC does not use "addCandidates" or "sendCandidates", it only uses "createOffer", "createAnswer", "setLocalDescription" and "setRemoteDescription", so candidates MUST be included in offers/answers. My problem was browser offer and aiortc peer answer did not include candidates.

To solve it, I had to create offer/answer again after browser starts sending ice candidates and ice candidate status changed to "checking".

Something like this: 

`// Getting ice candidate status change event handler
	localPeer.oniceconnectionstatechange = function(event) {
		trace("ICE Candidate State: " + localPeer.iceConnectionState);
		trace("ICE Gathering State: " + localPeer.iceGatheringState);
		
		// Create offer again and send it to remote peer with new candidates
		if(localPeer.iceConnectionState == "checking") {
			console.log("It is checking right now");
			localPeer.createOffer(offerOptions).then(
				function(offer) {
					//console.log('New offer created: ' + JSON.stringify(offer))
					localPeer.setLocalDescription(offer);
					sendNegotiation("offer", offer);
				},
				function(err) {
					console.log('Error creating new offer');
				}
			);
		}
	};
`

**Comment by jlaine** [comment]
Hi Charlie, indeed this is documented in the README : ICE Trickle isn't yet supported.

I plan to eventually I'd like to add support for this, the initial step being to add support for ICE trickle to aioice:
https://github.com/jlaine/aioice/issues/4

**Comment by CharlieHollow** [comment]
Hi @jlaine,

Its true, you documented it in the README, but it was not clear enough for me. This is why I've tried to connect both peers, making some tricks.

Anyway, any support for ICE trickle is appreciated. Hope you could update it soon.

Thanks so much.

In addition, a modification in RTCPeerConnection constructor to support adding custom STUN and TURN servers will be appreciated as well, as it is reflected in this issue: [jlaine/aiortc#13](https://github.com/jlaine/aiortc/issues/13)

**Comment by tartavull** [comment]
I believe I'm running onto the same issue. Is there any way to disable ICE Trickle on the browser?

**Comment by tartavull** [comment]
iceCandidatePoolSize does prefetching of ICE candidates avoiding sending an offer with no candidates
```
var pc = new RTCPeerConnection({
    sdpSemantics: 'unified-plan', //newer implementation of WebRTC
    iceServers: [{urls: 'stun:stun.l.google.com:19302'}],
    iceCandidatePoolSize: 2
});
```

**Comment by XingkaiEden** [comment]
I got the same issue. Because my project was originally written in JS which has a listener for ice candidates and then call back WebSocket to send it.

now, I have to change the plan.

Your solution really inspire me, thanks
