### ISSUE TITLE
SCTP: Support stream reconfiguration extension

### ISSUE THREAD

**Issue by lgrahl** [jlaine/aiortc#3]
[RFC 6525](https://trac.tools.ietf.org/html/rfc6525) is mandatory for data channels ~~and already used by aiortc but not announced during the handshake~~ but not supported by aiortc. There's no way to gracefully close a data channel.

**Comment by jlaine** [comment]
I'm not sure I follow, so far aiortc doesn't support reconfiguration, why should it announce it?

Presently this is the full list of chunks supported (they are all from plain RFC 4960):

https://github.com/jlaine/aiortc/blob/d356596cb80413b62c8b95cfc3b8230de5aa2aa9/aiortc/sctp.py#L208

**Comment by lgrahl** [comment]
You're correct. I've rephrased the issue.

**Comment by jlaine** [comment]
I believe closing DataChannels is now correctly implement in HEAD. I have performed tests with Firefox, and the DataChannels close properly regardless of whether Firefox or aiortc is the one requesting the close.
