### ISSUE TITLE
Get raw socket of data channel

### ISSUE THREAD

**Issue by alex-eri** [jlaine/aiortc#33]
Can I extract raw(low level or asincio stream) socket from data channel?

**Comment by jlaine** [comment]
I'm not sure what you are asking for, could you elaborate?

If the question is "can I access the underlying UDP socket" - no, that would be useless as data channels build upon DTLS and SCTP and you wouldn't be able to do anything with the raw data.

 If the question is "would it be possible to build a stream-like interface *on top* of the data channel" - then possibly but it does not exist currently.

**Comment by alex-eri** [comment]
ok, if control inband i would create file-like on top of data-channel. 

I want send files for example

Is it ok to send data bigger than MTU in one message? i.e. if i send 1500 bytes it recieved as one 1500 bytes message?

**Comment by jlaine** [comment]
You don't need to worry too precisely about the MTU size, the SCTP layer will perform fragmentation/re-assembly for you, so you can for instance use 4096 byte blocks.

NOTE: aiortc only supports ordered messages, which is exactly what you need for this use case.

I have committed a basic example of file transfer in a45786d31ec21b2ae4cbe3daf901a0cd2d98de08. It works, but isn't however fully satisfactory for large files as aiortc's Data Channel implementation doesn't report the amount of buffered data, and all data gets shoved straight down to the SCTP layer, which is not optimal.

**Comment by alex-eri** [comment]
I created [layer2vpn prototype](https://github.com/alex-eri/revpn) on top of aiortc. And it works!

Filetransfer should be implemented with [AbstractEventLoop.sendfile(transport, file, offset=0, count=None, *, fallback=True)](https://docs.python.org/3/library/asyncio-eventloop.html#file-transferring) in this case i asked for lower level api.

**Comment by jlaine** [comment]
That VPN example is very cool, would you mind contributing it to aiortc?

For file transfer, you could probably build an adapter on top of the data channel API. However as there is no standardised way of sending files (how to you convey file metadata? how do you agree end-of-file?) I don't think it will be built into aiortc.

**Comment by alex-eri** [comment]
VPN also can run faster with native readers, protocols.

First commit working. Now rewriting for pythonic ioctl (pytun is not really needed) and async reader for better event processing (now it uses much of cpu). 

Contributing it to aiortc possible only as examples because of VPN is not standartised in WebRTC.
Also it needs system tools for routing and address assigning, not crossplatform and so on.

**Comment by jlaine** [comment]
Ok never mind about the VPN demo if it still needs more work.

I'm going to close this issue as I think the original topic has been addressed.
