### ISSUE TITLE
support multiple video/audio tracks

### ISSUE THREAD

**Issue by petedaws** [jlaine/aiortc#38]
Excellent package.
referring to:
`raise InternalError('Only a single %s track is supported for now' % track.kind)` in `RTCPeerConnection`
I am wondering what it would take to implement multiple tracks for a peerConnection and what alternative is generally recommended for handling multiple video tracks in the interim?
Thanks Alot.

**Comment by jlaine** [comment]
I have put this off so far, as browsers are in the middle of a transition to "Unified Plan SDP" for multiple streams. I don't mind adding support for this, but not handling compatibility mode.

**Comment by tomas-berg** [comment]
Great package. Need multiple track too.

**Comment by jlaine** [comment]
Pull requests are welcome!

Recommended reading : https://tools.ietf.org/html/draft-roach-mmusic-unified-plan-00

**Comment by tomas-berg** [comment]
So, no SFU right now. Can You suggest the way it should be implemented, despite compatibility issues?

**Comment by jlaine** [comment]
Do you absoluely need multiple audio/video tracks on a *single* RTCPeerConnection? Until multi-track is supported, you could use several RTCPeerConnection.

**Comment by petedaws** [comment]
For me, it seems like the appropriate solution from a design perspective to
use multiple media tracks. However multiple peer connections is what I'm
using at the moment.

**Comment by jlaine** [comment]
Sure in the long run multiple media tracks make sense.

However unless someone makes the effort of reading the JSEP, putting together a pull request and doing interop testing with current and upcoming Chrome / Firefox versions it'll happen when I get round to it.

The key thing to get right is how transceivers on both side are matched up during initial negotiation and subsequent renegotiations.

**Comment by jlaine** [comment]
I have landed a patch which allows multiple audio/video tracks. I have added some unit tests to check `aiortc` works against itself.

I have not had a chance to interop it with Firefox or Chrome for lack of a sane example, so feedback is welcome.
