### ISSUE TITLE
how to send offer data to remote server?

### ISSUE THREAD

**Issue by m-karbasi** [jlaine/aiortc#43]
hello
I`m new in RTC.In your examples folder,I saw you`ve made the index html and client.js files and by these pages clients can send offer data to the server to connect together.
If I want to put these two pages as clientside and send offer data from client to server, how to do this work?

**Comment by jlaine** [comment]
I'm sorry but I don't understand what you're trying to do, could you please rephrase the question?

**Comment by m-karbasi** [comment]
Sure, Now you have this line in server.py in this path (aiortc/examples/server):
```python
app.router.add_get('/', index)
```
I mean if I want to have codes of index.html and client.js files on a client machine and want to use offer as remote API,
for example, I want to change this block of code in client.js:
```javascript
var offer = pc.localDescription;
document.getElementById('offer-sdp').textContent = offer.sdp;
return fetch('http://remote-host:8080/offer', {
body: JSON.stringify({
'offer': offer,
'call_id': '232bsdh65cvcss907687',
'user_id': '1',
}),
headers: {
'Content-Type': 'application/json'
},
method: 'POST'
});

```
unfortunately the connection is not established.
could you please guide me how to do that?
Thanks in advance

**Comment by jlaine** [comment]
I still don't understand why you want the HTML + JS to be on the client side, the example provided is perfectly capable of serving them to a remote machine.

Anyway : open your browser's console and you'll see why the it's not working. You are attempting to perform a cross-origin fetch() which is blocked by the browser, so the server never even gets the offer.

**Comment by m-karbasi** [comment]
I fixed error related to cross-origin but I have new problem. as if there is not data channel.
I got screen shot from response in cosole of the browser, could you please see it?
![screenshot from 2018-07-25 17-09-28](https://user-images.githubusercontent.com/32981547/43201874-0052d6be-902f-11e8-9fdd-7216312e8d02.png)

what should I do to solve this issue

**Comment by jlaine** [comment]
Does the `server` example in its *unmodified* form work OK ?

**Comment by sogand145** [comment]
same problem too. I tested with your sample in server folder, but I couldn`t get above results like the picture, actually there is only offer data, not answer.
 Could you please let me know how to fix this issue?
I searched about STUN server, TURN server and Signaling server and found that in real examples, these servers must be exist. there is allways Signaling server for transfering datachannel (offer & answer data ) and STUN/TURN server must be defined for sending media between two peers.
I saw your codes that you had been defined STUN server :
```python
@classmethod
    def getDefaultIceServers(cls):
        """
        Return the list of default :class:`RTCIceServer`.
        """
        return [RTCIceServer('stun:stun.l.google.com:19302')]
```
and in there was iceservers variable in code below in rtcconfiguration.py:
```python
@attr.s
class RTCConfiguration:
    """
    The :class:`RTCConfiguration` dictionary is used to provide configuration
    options for an :class:`RTCPeerConnection`.
    """
    iceServers = attr.ib(default=None)
    "A list of :class:`RTCIceServer` objects to configure STUN / TURN servers."
```
could you please tell me where to define iceservers?
and are these servers defined by aiortc package?

Regards,

**Comment by jlaine** [comment]
Adding unrelated questions to a closed issue is unhelpful

**Comment by t-walker-wei** [comment]
> I fixed error related to cross-origin but I have new problem. as if there is not data channel.
> I got screen shot from response in cosole of the browser, could you please see it?
> ![screenshot from 2018-07-25 17-09-28](https://user-images.githubusercontent.com/32981547/43201874-0052d6be-902f-11e8-9fdd-7216312e8d02.png)
> 
> what should I do to solve this issue

Hello, I also face this problem now.I want to separate the html part to another server instead of aiohttp.Did you solve this?
