### ISSUE TITLE
send only  peerconnection does not work.

### ISSUE THREAD

**Issue by notedit** [jlaine/aiortc#44]
in the python side, aiortc just receive medias,  does not do `addTrack`,  code like this

```python

@app.route('/offer', methods=['POST'])
async def offer(request):

    data = request.json 

    offer = RTCSessionDescription(sdp=data['sdp'],type=data['type'])

    pc = RTCPeerConnection()
    pc._consumers = []
    pcs.append(pc)

    @pc.on('track')
    def on_track(track):
        if track.kind == 'video':
            print('on_track')
            asyncio.ensure_future(consume_video(track))
            print('on_track')

    await pc.setRemoteDescription(offer)
    answer = await pc.createAnswer()
    await pc.setLocalDescription(answer)

    print('answer', answer)

    return json({
            'sdp': pc.localDescription.sdp,
            'type': pc.localDescription.type
        })

```

client side code  

```javascript

	var pc = new RTCPeerConnection();

	pc.onaddstream = function(event) {
		console.debug("pc::onAddStream",event);
		//Play it
		addVideoForStream(event.stream);
	};

	pc.onremovestream = function(event) {
		console.debug("pc::onRemoveStream",event);
		//Play it
		removeVideoForStream(event.stream);
	};

    const stream = await navigator.mediaDevices.getUserMedia({
        audio: false,
        video: true
    });

    addVideoForStream(stream,true);

    stream.getTracks().forEach(function(track) {
        pc.addTrack(track, stream);
    });

    const offer = await pc.createOffer({
        offerToReceiveAudio: true,
        offerToReceiveVideo: true
    });

    await pc.setLocalDescription(offer);

    const rawResponse = await fetch('http://localhost:5000/offer', {
        method: 'POST',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            type: 'offer',
            sdp : offer.sdp
        })
    });
    
    const content = await rawResponse.json();

    console.log(content)

    const answer = new RTCSessionDescription({
        type : 'answer',
        sdp	: content.sdp
    });
    
    //Set it
    await pc.setRemoteDescription(answer);

```

After do offer/answer,  there is no media coming  from  browser  side. 

In the `chrome://webrtc-internals`,  it shows  audio/video track with no data.

Thanks.

**Comment by notedit** [comment]
after some test,  It seems is a bug with ice .   Sometimes the ICE connection state just stop with checking state.

**Comment by jlaine** [comment]
Could you paste some more logs to figure out what's going on, as I have too litle information to help here.

**Comment by notedit** [comment]
I made  some change  as your demo code https://github.com/jlaine/aiortc/blob/master/examples/server/client.js#L41,
do offer/answer  after ice gathering complete,  it solves this problem.

Maybe we should add some docs about this.

**Comment by jlaine** [comment]
I don't have access to your source code but this doesn't look like an aiortc issue:

- either you collect all ICE candidates and send them to aiortc in the initial offer (like the `server` example does)

- or you use ICE trickle on the browser side, but then you need to send the ICE candidates by some other means and call RTCPeerConnection.addIceCandidate (like the `apprtc` example does)

If you don't send the browser's candidates to aiortc, it has now way of establishing the connection.
