### ISSUE TITLE
what's corresponding peerconnection.onicecandidate event and handler with JS?

### ISSUE THREAD

**Issue by KuimingYu** [jlaine/aiortc#46]
what's corresponding peerconnection.onicecandidate event and handler with JS?
If there is not this kind of event, how to implement it?

Thanks.

**Comment by KuimingYu** [comment]
Sorry, duplicate with jlaine/aioice#4

**Comment by jlaine** [comment]
For now we support "half trickle", so the "onicecandidate" event is never fired.
