### ISSUE TITLE
Latency with data channel

### ISSUE THREAD

**Issue by eric-hth** [jlaine/aiortc#48]
Hello,

We have a server that send data every 30 ms. on the other side we have a client receiving these data.

With 0.9.1 the client receive data every 30 ms

With 0.9.3 the client receive data by batches. We have nothing for 200ms then several data within 1 or 2 ms.

Is it normal or a bug ?

Regards,

**Comment by jlaine** [comment]
Could you provide a minimal example so that I can reproduce this issue? This change in behaviour is probably a side effect of the performance improvements which landed in 0.9.2.

**Comment by jlaine** [comment]
I have reworked the `datachannel-cli` example to measure round-trip delays on a simple ping/pong.

In my experience the total round-trip delay on localhost is ~5ms once the datachannel is up:

```
channel(chat) - created by local party
channel(chat) > ping
channel(chat) < pong
 RTT 3.23 ms
channel(chat) > ping
channel(chat) < pong
 RTT 6.31 ms
channel(chat) > ping
channel(chat) < pong
 RTT 5.79 ms
channel(chat) > ping
channel(chat) < pong
 RTT 4.94 ms
channel(chat) > ping
channel(chat) < pong
 RTT 5.28 ms
channel(chat) > ping
channel(chat) < pong
 RTT 5.78 ms
channel(chat) > ping
channel(chat) < pong
 RTT 3.02 ms
channel(chat) > ping
channel(chat) < pong
 RTT 5.50 ms
channel(chat) > ping
channel(chat) < pong
 RTT 5.11 ms
channel(chat) > ping
channel(chat) < pong
 RTT 1.77 ms
channel(chat) > quit
channel(chat) < quit
```

**Comment by jlaine** [comment]
I have made some further improvements in 6e6af3bca425924a0af83ae48d880c3d9d22853e which both reduced latency and increased throughput:

  - Roundtrip time: 5ms before, 3ms after
  - Throughput: 50Mbps before, 67Mbps after

If you have further information I'll look at it, but from my tests it all looks good.
