### ISSUE TITLE
not able to run the server when in different local net

### ISSUE THREAD

**Issue by zhangguangfengz** [jlaine/aiortc#49]
Hi, jlaine
  Can you give me some advise about the remote video stream transport?
  When I in different local net,the server example not work

**Comment by jlaine** [comment]
I don't understand the issue can you please elaborate?

**Comment by jlaine** [comment]
Closing due to lack of feedback from the submitter

**Comment by mijime** [comment]
> When I in different local net,the server example not work

Have you set up an ICE server?

This PR is helpful
https://github.com/jlaine/aiortc/pull/23
https://github.com/jlaine/aiortc/blob/master/aiortc/rtcconfiguration.py

**Comment by zhangguangfengz** [comment]
@mijime 
       Thank you mijime,That's helpful. and thanks jlaine for the aiortc.

**Comment by raghavendrajain** [comment]
@walle-z Can you make it work for remote video chat? if so, can you please suggest the steps? thank you!
