### ISSUE TITLE
SCTP: Parse destination port

### ISSUE THREAD

**Issue by lgrahl** [jlaine/aiortc#5]
It seems the destination port is not parsed from the SDP. This is how my offer looks like:

```
{
   "type":"offer",
   "sdp":"v=0\r\no=sdpartanic-rawrtc-0.2.1 1371244329 1 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=ice-options:trickle\r\na=group:BUNDLE rawrtc-sctp-dc\r\nm=application 9 DTLS\/SCTP 6000\r\nc=IN IP4 0.0.0.0\r\na=mid:rawrtc-sctp-dc\r\na=sendrecv\r\na=ice-ufrag:KH0HgbiF8NhcfZj8\r\na=ice-pwd:baklGzPiRBxlhfUq3Dm1fvNiqM1r28fM\r\na=setup:actpass\r\na=fingerprint:sha-256 36:13:5E:68:CB:C9:D0:43:9C:C5:32:41:F4:47:04:3F:E2:84:3A:AB:0E:78:02:FD:37:51:9F:32:10:D1:14:A2\r\na=tls-id:zLqLLaRkwjyxQKlfO9Tv0dva2McaHRID\r\na=sctpmap:6000 webrtc-datachannel 65535\r\na=max-message-size:0\r\n[...]\r\na=end-of-candidates\r\n"
}
```

Be aware, the SCTP port may also come in the form of

```
a=sctp-port:6000
```

in the associated media line.

**Comment by lgrahl** [comment]
And probably in gazillions of other forms. This is SDP after all. :smirk:

**Comment by jlaine** [comment]
Oh, it's parsed alright.. it's just not used ;)

**Comment by jlaine** [comment]
To be honest there is deeper underlying issue here which is that aiortc is currently unable to multiplex multiple SCTP associations over a single DTLS transport.

Also I'm starting to lose my mind reading :
https://github.com/w3c/ortc/issues/625

I am now really confused as to whether local / remote ports match, and how RTCSctpTransport relates to an SCTP association.

**Comment by lgrahl** [comment]
Don't worry, no one is able to multiplex multiple SCTP transports/virtual sockets (if you meant that because associations are of course multiplexed by port numbers). I also don't see a single use case for this.

In ORTC: You create an `RTCSctpTransport` by the `RTCDtlsTransport` and an optional port number. If that is not set, the local port will default to whatever you want it to default. You set the remote port number when invoking the `start` method.

**Comment by lgrahl** [comment]
An `RTCSctpTransport` is an SCTP association.
