### ISSUE TITLE
using Aiortc on windows 10

### ISSUE THREAD

**Issue by jmh-aira** [jlaine/aiortc#50]
Hi, in the docs you give details on linux/mac for installing the requirements.  How can I use this python module on windows? what libraries need to be installed? Thanks.

**Comment by rckprtr** [comment]
Alright it looks like it needs opus codec in the build path, Im figuring this out now also.  


`    aiortc.codecs._opus.c
    build\temp.win32-3.6\Release\aiortc.codecs._opus.c(493): fatal error C1083: Cannot open include file: 'opus/opus.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status `

**Comment by jlaine** [comment]
I don't have access to a Windows machine, so I am unable to provide guidance here.

**Comment by jlaine** [comment]
As Windows lacks a package manager to install the required dependencies (codecs), the best option for now is probably to use the Windows Subsystem for Linux:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

If someone is willing to provide step by step instructions on how to install the opus and vpx dependencies for Windows, please re-open this issue!

**Comment by rckprtr** [comment]
Hey guys, I opened my Ubuntu 10 Bash Terminal and typed:

apt install opus-devel
apt install libvpx-dev

aiortc builds and installs successfully

**Comment by JackD83** [comment]
I got it working on native Windows 10 without WSL:

You need VisualStudio 2015 (not 2017 or 2019)

Make sure you choose the correct architecture for your libs!

PyAV preperations:
Download fmpeg builds from here: https://ffmpeg.zeranoe.com/builds/
You need the shared and the dev package. Unpack both to e.g. C:\ffmpeg
Add C:\ffmpeg\bin and C:\ffmpeg\lib to PATH


Opus:
Download source from http://opus-codec.org/downloads/
The source builds without problems with VS2015. Build opus as a shared release lib to get opus.lib and opus.dll

Add opus.lib to python/libs
Add opus,dll to python/DLLs
copy header files to pyton/include/opus

VPX:
Get the pre-build vpx here: https://github.com/ShiftMediaProject/libvpx/releases
Copy the vpx.dll to your python dir (Dlls folder did not work for me)
copy the files from lib to python/libs
copy the vpx folder from include to python/include


Now you should be able to install everything with:

pip install aiohttp aiortc opencv-python --global-option=--ffmpeg-dir=C:\ffmpeg

**Comment by mas-dse-dhpancha** [comment]
Opus:
Download source from http://opus-codec.org/downloads/
The source builds without problems with VS2015. Build opus as a shared release lib to get opus.lib and opus.dll

Hi JackD83,
Just need some clarification. Which download did you use to get opus.lib and opus.dll? Was it from  "Source code: opus-1.3.1.tar.gz"?

How did you get those two files from there? Thanks.

**Comment by sushrutt12** [comment]
For everyone facing problems building OPUS:

You can do either of the following:

- **To build on your own using VS2017**
`git clone https://git.xiph.org/opus.git`
`cd opus\win32\VS2015`
Open opus.sln in Visual Studio
Right click project build, go to configuration manager & select debug dll /release dll and your windows platform 32/64
If you dont select dll in the configuration a dll file wont be created.
Header files can be copied from opus\include

- **To just copy the related files you can refer to [this](https://github.com/sushrutt12/Opus) repository**
