### ISSUE TITLE
aiortc.contrib not found

### ISSUE THREAD

**Issue by danhzhu** [jlaine/aiortc#53]
When I compiling the "python apprtc.py" with python 3.6.6 in the example apprtc, there raises the issue with aiortc.contrib: 
Traceback (most recent call last):
  File "apprtc.py", line 14, in <module>
    from aiortc.contrib.media import frame_from_bgr
ModuleNotFoundError: No module named 'aiortc.contrib'

**Comment by alexander-akhmetov** [comment]
It seems like it's fixed, but not released yet: https://github.com/jlaine/aiortc/pull/47
If you install the package directly from git directly, it works.

@jlaine Can you release a fixed version, please?

**Comment by jlaine** [comment]
Version 0.9.4 is being built and will be on pypi in a couple of minutes.

**Comment by alexander-akhmetov** [comment]
Thank you!
