### ISSUE TITLE
Opus usage

### ISSUE THREAD

**Issue by tomaszba** [jlaine/aiortc#54]
I'm looking for an example how to use an opuc codec attached to the source code.

My idea is to change server example to write sound not as a RAW WAV file but as a compressed one.

How to do that?

Regards,
Tom

**Comment by jlaine** [comment]
Hi Tom,

The code that interfaces with the opus codec is "private API" at this stage, in the sense that I make no guarantees about the API staying as it is. Also that code only deals with passing data on to the Opus codec, and doesn't do anything related to container file formats.

I think you might want to look at opuslib which might do what you want:

https://github.com/OnBeep/opuslib
