### ISSUE TITLE
input/output raw rtp packet api 

### ISSUE THREAD

**Issue by notedit** [jlaine/aiortc#55]
Hi:

I am thinking whether we can have the raw input/output raw rtp packet api,  use other media lib/framework(ffmpeg, gstreamer) to handle media,

**Comment by jlaine** [comment]
I'm not sure outputting the raw RTP is very useful, how would things like RTCP reports be handled/generated? Maybe you can elaborate on your usecase?

In the meantime if you absolutely want to do this, one way would be to monkey-patch `RTCRtpReceiver._handle_rtp` and  `RTCRtpReceiver._handle_rtcp` which will give you the decoded RTP/RTCP packets. If you want to convert them back to bytes you can use `bytes(packet)`.

**Comment by notedit** [comment]
user case like:  save to  file,  forward to  rtsp server without another decode/encode.  

 monkey-patch  is way to do this.

**Comment by jlaine** [comment]
Saving to file: ok, sure.

As to forwarding to another server, I'm not sure this would be the right place to do it. I agree you want to skip the codec decode/encode step, but I think you would still like to retain the benefit of the jitter buffer and the RTCP-based retransmission (which I'm currently implementing). For this usecase I think it would be more useful to have an API which hands you re-assembled (but not decoded) audio/video frames.

Anyway I'll close this issue for now, please do leave a comment if you have some additional feedback.
