### ISSUE TITLE
Data channel string messages encoding

### ISSUE THREAD

**Issue by lgrahl** [jlaine/aiortc#6]
The encoding should be UTF-16 to be compatible with [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString).

**Comment by jlaine** [comment]
Are you sure that's correct? See:

https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13#page-11

```
    WebRTC String:  to identify a non-empty JavaScript string encoded in
      UTF-8.

   WebRTC String Empty:  to identify an empty JavaScript string encoded
      in UTF-8.

   WebRTC Binary:  to identify a non-empty JavaScript binary data
      (ArrayBuffer, ArrayBufferView or Blob).

   WebRTC Binary Empty:  to identify an empty JavaScript binary data
      (ArrayBuffer, ArrayBufferView or Blob).
```

**Comment by lgrahl** [comment]
Good catch. You are in fact correct. For reference, this is the code in Firefox: https://dxr.mozilla.org/comm-central/source/mozilla/dom/base/nsDOMDataChannel.cpp#184
