### ISSUE TITLE
Support MediaStreamTrack events

### ISSUE THREAD

**Issue by saluto** [jlaine/aiortc#60]
I tried to handle the `MediaStreamTrack.onended` event (see [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/onended)) on a received track in `aiortc`.
But it seems that no events for `MediaStreamTrack` are supported yet. Is that right? Is there any other way to detect them? 
At least for my usecase that's a major problem. Supporting events like `started`, `ended`, etc. for `MediaStreamTrack`, as documented [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack), would be really useful.

**Comment by jlaine** [comment]
Which MediaStreamTrack are we talking about? The want that represents the remote party's media, or the one you write to send media to the remote party?

**Comment by saluto** [comment]
I mean the remote/incoming stream. Because I want to detect when an incoming track was ended by the remote party (while the peer connection and stream is still alive).

**Comment by jlaine** [comment]
OK I'll look into it. Could you elaborate on how you plan to use these events?

The 'ended' event is interesting, but I'm wondering if `RemoteStreamTrack.recv()` shouldn't also raise an exception, at otherwise a media consumer will stay blocked forever

**Comment by saluto** [comment]
Right, in that case an exception makes sense. An explicit 'ended' event would still be useful, to handle ended remote tracks in a clean way. (In my usecase the remote client should be able to end and switch tracks, while the python client should remove ended remote tracks from its processing pipeline.)

**Comment by saluto** [comment]
Thanks for working on that!
I just noticed, that I also need it "the other way round", meaning `MediaStreamTrack.stop()` (see [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop)) for local tracks, and perhaps `RTCPeerConnection.removeTrack(sender)` (see [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/removeTrack)). Should I open a new issue for that?

**Comment by jlaine** [comment]
I'm not done yet with emitting 'ended', there are cases where it won't fire (like tearing down the peer connection while it's running). I also don't understand when 'started' is supposed to fire, the MDN docs say nothing about it, so I guess I need to go look at the actual specs.

When you say you want to call MediaStreamTrack.stop(), is this again on the remote media stream track? What's the purpose?

**Comment by saluto** [comment]
I think, 'started' is not an official event on `MediaStreamTrack`, only 'mute', 'unmute', 'overconstrained', 'ended', as listed [here](https://www.w3.org/TR/mediacapture-streams/#event-summary).
And maybe [this](https://www.w3.org/TR/mediacapture-streams/#life-cycle-and-media-flow) helps for the 'ended' event.

`MediaStreamTrack.stop()` I want to call on the _local_ track. This should set the track state to 'ended' (see [here](url)) and the remote (receiving) client should be able to detect this by an 'ended' event. No further data should be sended through that track.

**Comment by jlaine** [comment]
OK let's forget about "started" then.

For the second point, as *you* provide the local track by subclassing `MediaStreamTrack` I don't think stop() makes any sense : it would do nothing. My suggestion is for you to instead stop the RTCRtpTransceiver, which will send a BYE to the remote party.

**Comment by saluto** [comment]
Great, thanks! I will try that.
