### ISSUE TITLE
Could aiortc run on micropython?

### ISSUE THREAD

**Issue by joeky888** [jlaine/aiortc#61]
From https://github.com/micropython/micropython

> MicroPython implements the entire Python 3.4 syntax (including exceptions, with, yield from, etc., and additionally async/await keywords from Python 3.5)

Could aiortc run on micropython?

Thanks. :)

**Comment by jlaine** [comment]
I have absolutely no idea to be honest, having never used micropython. However the main problem you are likely to face is unrelated to the Python code itself: if you are operating in a highly constrained environment it's likely you won't have the required codecs to encode/decode audio and video.

**Comment by lgrahl** [comment]
But the data channel part should most definitely run. If not, I assume only minor changes are required.

**Comment by jlaine** [comment]
I don't really have plans for making aiortc available piecewise, it's going to come back and bite me in the ass along the lines "hey aiortc installed fine, but I negotiate any media". How would you propose handling Python dependencies in setup.cfg if 99% of the users should have libsrtp2 and 1% not?

**Comment by lgrahl** [comment]
The only viable options I can see is splitting up the module into several smaller ones where aiortc requires all of them (`aiortc.base`, `aiortc.data`, ...). I'm not proposing to do that now but if more people request it, it can be done and from my own experience it's not painful if done with caution.

**Comment by joeky888** [comment]
> I don't really have plans for making aiortc available piecewise

Ok, thanks!

**Comment by lgrahl** [comment]
@joeky888 Out of curiosity: What device would you like to run it on?

**Comment by joeky888** [comment]
arm64 Linux, no python3 and very limited hardware.

I can only use C or C++ or Go or Python2 or Micropython.

In the end I choose https://github.com/pions/webrtc and it works great.

Never tried aiortc though.

**Comment by jlaine** [comment]
That go implementation is really cool!

Some interesting takeaways:

- they seem to have avoided libsrtp altogether. The SRTP implementation is suprisingly compact (though admitedly they leverage existing crypto primitives), which leaves me wondering whether libsrtp is just insanely bloated or whether the go implementation took shortcuts.

- they decided to leave media encoding/decoding to the user, for instance using gstreamer. That's an interesting choice, as it cuts down the dependencies drastically.

I don't seem to find any kind of jitter buffer, RTCP or NACK/PLI support, which leaves me wondering how it performs in lossy (a.k.a real) networks.

**Comment by joeky888** [comment]
> for instance using gstreamer

Gstreamer is a heavyweight dependency for me, I have managed to replace it with just libopus and libasound2.

```diff
diff --git a/examples/gstreamer-receive/jsfiddle/demo.js b/examples/gstreamer-receive/jsfiddle/demo.js
index 407022c..04b4d07 100644
@@ -11,7 +11,7 @@ var log = msg => {
   document.getElementById('logs').innerHTML += msg + '<br>'
 }
 
-navigator.mediaDevices.getUserMedia({video: true, audio: true})
+navigator.mediaDevices.getUserMedia({video: false, audio: true})
   .then(stream => pc.addStream(document.getElementById('video1').srcObject = stream))
   .catch(log)
 
diff --git a/examples/gstreamer-receive/main.go b/examples/gstreamer-receive/main.go
index 05174db..2466112 100644
@@ -8,9 +8,10 @@ import (
 	"bufio"
 	"encoding/base64"
 
+	"github.com/cocoonlife/goalsa"
 	"github.com/pions/webrtc"
-	"github.com/pions/webrtc/examples/gstreamer-receive/gst"
 	"github.com/pions/webrtc/pkg/ice"
+	"gopkg.in/hraban/opus.v2"
 )
 
 func main() {
@@ -46,14 +47,54 @@ func main() {
 
 	// Set a handler for when a new remote track starts, this handler creates a gstreamer pipeline
 	// for the given codec
+
+	const sampleRate = 48000
+	const channels = 1
+
+	dec, err := opus.NewDecoder(sampleRate, channels)
+	if err != nil {
+		fmt.Println("Decoder error")
+		panic(err)
+	}
+
+	out, err := alsa.NewPlaybackDevice("default", channels, alsa.FormatS16LE, sampleRate, alsa.BufferParams{})
+	if err != nil {
+		panic(err)
+	}
+
+	// require ALSA device
+	if out == nil {
+		fmt.Println("Device is nil!!")
+	} else {
+		fmt.Println(out)
+	}
+	// close device when finished
+	defer out.Close()
+
 	peerConnection.Ontrack = func(track *webrtc.RTCTrack) {
 		codec := track.Codec
 		fmt.Printf("Track has started, of type %d: %s \n", track.PayloadType, codec.Name)
-		pipeline := gst.CreatePipeline(codec.Name)
-		pipeline.Start()
+
+		pcm := make([]int16, 100000)
 		for {
 			p := <-track.Packets
-			pipeline.Push(p.Raw)
+
+			_, err := dec.Decode(p.Payload, pcm)
+
+			if err != nil {
+				fmt.Println("Decode error")
+				panic(err)
+			}
+
+			if pcm != nil {
+				// play!
+				out.Write(pcm)
+
+				fmt.Println("before:")
+				fmt.Println(p.Payload)
+				fmt.Println("after:")
+				fmt.Println(pcm)
+			}
 		}
 	}
```
