### ISSUE TITLE
Examples incompatible with aiortc 0.9.7

### ISSUE THREAD

**Issue by eduardofamendes** [jlaine/aiortc#67]
Hi,

I am trying to test the example server, but it gives me the error:
raceback (most recent call last):
  File "server.py", line 17, in <module>
    from aiortc.contrib.media import (MediaBlackhole, MediaPlayer, MediaRecorder,
ImportError: cannot import name 'MediaBlackhole'

I can se in the aiortc the MediaBlackhole was added in the current master version 0.9.8, that is not available to install with pip yet. How can I use this example, and all the code in general?

Best,

Eduardo Mendes

**Comment by jlaine** [comment]
Hi! I'm finishing a round of tests and will push aiortc 0.9.8 out of the door ASAP.

**Comment by eduardofamendes** [comment]
Thank you. By ASAP do you mean 15 minutes or a week?

**Comment by jlaine** [comment]
It's on pypi now :)
