### ISSUE TITLE
Send OpenCV Frame to WebRTC Server for MultiViewing

### ISSUE THREAD

**Issue by ashuezy** [jlaine/aiortc#70]
I am trying to broadcast OpenCV Frame to a Media Server. 

1) First I am confused which media server i should use. This is to be used by many people.
2) Can i use aiortc library to send OpenCV frame to Red5 media server or would you recommend any other ?

Thanks.

**Comment by jlaine** [comment]
No idea for the choice of server, you're in a better position than me to decide as you know your requirements.

Red5 seems only marginally connected to WebRTC (their page says they are "working on WebRTC as part of GSoC") so I'm not sure how aiortc fits into the picture?

**Comment by ashuezy** [comment]
@jlaine 
Thanks for replying.

I am using your server.py demo from examples. It is reading from webcam and i want to put frame from opencv which are coming from RTSP. So i just want to put the "img" variable to the webrtc server.

```
import cv2 
import numpy as np

face_cascade = cv2.CascadeClassifier('./models/haarcascade_frontalface_default.xml')
rtsp_url = '<rtsp url>'
cap = cv2.VideoCapture(rtsp_url)


while True: 
 
    # reads frames from a camera
    ret, img = cap.read() 
 
    # convert to gray scale of each frames
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
    # Detects faces of different sizes in the input image
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
 
    for (x,y,w,h) in faces:
        # draw rectangle on face(s) found
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,255,0),2) 
        roi_color = img[y:y+h, x:x+w]
 
 
    # Display an image in a window
    cv2.imshow('img',img)
 
    # Wait for Esc key to stop
    k = cv2.waitKey(1)
    if k == 27:
        break
 
# Close the window
cap.release()
 
# De-allocate any associated memory usage
cv2.destroyAllWindows() 
```

**Comment by ashuezy** [comment]
Is there an option put my modified frames to WebRTC
Kindly reply...

**Comment by ashuezy** [comment]
Let me explain step by step:
1. A standalone python application opens rtsp url from CCTV camera.
2. It modifies the Frame by drawing Rectangles.
3. It sends the modified frames to a WebRTC server like Kurento to be viewed in browser.
4. This application has a web interface for multiple people for viewing.
5. Application fetches the video from Kurento.

**Comment by jlaine** [comment]
I'm still no closer to understanding. What do you mean at step 3 by "sends to a WebRTC server". How? Using WebRTC?  If so, using what signaling (i.e. how are offers and answers exchanged)?

WebRTC doesn't specify how signaling occurs, so this will be specific to your application.

**Comment by jlaine** [comment]
Closing, no response from submitter in 15 days
