### ISSUE TITLE
Ice negotiation fail on firefox.

### ISSUE THREAD

**Issue by mbalamat** [jlaine/aiortc#72]
I am trying to build a video broadcast app to share a computer's default camera with many peers.
My network setup is pretty basic, my computer acts as one of the peers and my computer's browser (chrome / firefox) as the other.
I was wondering why I get this error when I am using firefox. Everything works fine on chrome.

> ========Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Task exception was never retrieved
future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /usr/local/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py:463> exception=ConnectionError('ICE negotiation failed')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcpeerconnection.py", line 468, in __connect
    await iceTransport.start(self.__remoteIce[transceiver])
  File "/usr/local/lib/python3.7/site-packages/aiortc/rtcicetransport.py", line 265, in start
    await self._connection.connect()
  File "/usr/local/lib/python3.7/site-packages/aioice/ice.py", line 385, in connect
    raise ConnectionError('ICE negotiation failed')
ConnectionError: ICE negotiation failed

The code to reproduce this error can be found here https://github.com/mbalamat/aiortc-broadcast-demo.
Thanks for this awesome lib.

**Comment by jlaine** [comment]
I had a quick look, and it looks as though Firefox is not responding to the STUN requests, I'm not sure why yet. I fired up wireshark and I see ICMP packets coming back with "destination unreachable".

A note : your code does not work with the latest aiortc, `frame_from_bgr` has been renamed to `video_frame_from_bgr`. Also, the next version of aiortc will *require* the `pts` and `time_base` attributes on VideoFrames.

Assuming we get this demo to work, would you consider relicensing it under the MIT license so we can ship it with aiortc?

**Comment by jlaine** [comment]
Adding a .catch() in client.js after setRemoteDescription reveals the problem:

`DOMException: "Answer tried to set recv when offer did not set send"`

It's true, aiortc doesn't yet support "sendonly", I'll try to fix this.

**Comment by AndrewKralovec** [comment]
@jlaine , was video_frame_from_bgr renamed again? I'm also trying to broad cast multiple webcams to the same browser / server.

**Comment by jlaine** [comment]
video_frame_from_bgr was removed about 6 months ago when I switched to PyAV's VideoFrame class, which features several helpers to convert to / from ndarray:

https://docs.mikeboers.com/pyav/develop/api/video.html#module-av.video.frame

Try: VideoFrame.from_ndarray(the_array, format="bgr24")
