### ISSUE TITLE
Failed building wheel for av

### ISSUE THREAD

**Issue by AboNawaF474** [jlaine/aiortc#74]
**Hello

I try to test "aiortc"**
https://github.com/jlaine/aiortc/tree/master/examples/server

**But I have this error:** ModuleNotFoundError: No module named 'aiortc'

**After install this packages**
$ pip install aiohttp aiortc opencv-python

**This error appears:**

Failed building wheel for av
  Running setup.py clean for av
Failed to build av
Installing collected packages: av, aiortc
  Found existing installation: av 0.4.0
    Uninstalling av-0.4.0:
      Successfully uninstalled av-0.4.0
  Running setup.py install for av ... error
    Complete output from command /Users/abonawaf..../anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/cn/_x7q0ck11jx0ngtcgddw_8p80000gn/T/pip-install-p40urdnq/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/cn/_x7q0ck11jx0ngtcgddw_8p80000gn/T/pip-record-jyqsw_l3/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/av
    copying av/deprecation.py -> build/lib.macosx-10.7-x86_64-3.6/av
    copying av/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av
    copying av/__main__.py -> build/lib.macosx-10.7-x86_64-3.6/av
    creating build/lib.macosx-10.7-x86_64-3.6/av/video
    copying av/video/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/video
    creating build/lib.macosx-10.7-x86_64-3.6/av/codec
    copying av/codec/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/codec
    creating build/lib.macosx-10.7-x86_64-3.6/av/container
    copying av/container/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/container
    creating build/lib.macosx-10.7-x86_64-3.6/av/audio
    copying av/audio/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/audio
    creating build/lib.macosx-10.7-x86_64-3.6/av/subtitles
    copying av/subtitles/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/subtitles
    creating build/lib.macosx-10.7-x86_64-3.6/av/filter
    copying av/filter/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/filter
    creating build/lib.macosx-10.7-x86_64-3.6/av/data
    copying av/data/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/av/data
    running build_ext
    running reflect
    running config
    pkg-config is required for building PyAV
    
    ----------------------------------------
  Rolling back uninstall of av
Command "/Users/abonawaf..../anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/cn/_x7q0ck11jx0ngtcgddw_8p80000gn/T/pip-install-p40urdnq/av/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/cn/_x7q0ck11jx0ngtcgddw_8p80000gn/T/pip-record-jyqsw_l3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/cn/_x7q0ck11jx0ngtcgddw_8p80000gn/T/pip-install-p40urdnq/av/

**Comment by jlaine** [comment]
The error message seems quite clear: you need `pkg-config`, can you let me know if this helps?

`brew install pkg-config`

If so I'll add it to the README.

**Comment by smanschi** [comment]
I had the same issue and yes, it helps :-). I also had to install a couple of other packages in order to get it work, as they were not installed on my default Ubuntu 18.04 OS. Unfortunately, I did not write them down.

**Comment by jlaine** [comment]
Do you recall if there were any which are not already mentioned in the README?

**Comment by AboNawaF474** [comment]
> The error message seems quite clear: you need `pkg-config`, can you let me know if this helps?
> 
> `brew install pkg-config`
> 
> If so I'll add it to the README.

Successfully built av
Installing collected packages: av, aiortc
  Found existing installation: av 0.4.0
    Uninstalling av-0.4.0:
      Successfully uninstalled av-0.4.0
Successfully installed aiortc-0.9.8 av-0.5.3

**Yes help me install module 'aiortc'
But I had another problem :-(** 

https://i.postimg.cc/ydhdbTg5/Screen_Shot_2018-10-04_at_9.53.14_PM.png

https://i.postimg.cc/kGn43tW5/Screen_Shot_2018-10-04_at_9.52.46_PM.png

**Comment by smanschi** [comment]
> 
> 
> Do you recall if there were any which are not already mentioned in the README?

The only thing I remember was that I had to install libsm-dev in order to run the server example. The library was not needed for pip installing the package, though.

**Comment by Vin-itall** [comment]
This helped me build it successfully on macOS :


conda install av -c conda-forge

brew install ffmpeg pkg-config

pip install aiohttp aiortc opencv-python
