### ISSUE TITLE
[QUESTION] Trying python WebRTC first time

### ISSUE THREAD

**Issue by sarkarchandan** [jlaine/aiortc#77]
Hi Jeremy,

I am student and trying to use WebRTC with python first time. I have come across your repository and wanted to try try and learn it. I am also new to python as well.

I have grabbed the videostream-cli example and tried to add a bit of code to make it work for sending some video from web cam as a beginner step. I have noticed that you have made some recent commits to the code but I am trying to use the older one where you have separate run_offer and run_answer functions.

Here is what I have tried.
 
**#Added a class in the cli.py**

class CameraVideoStreamTrack(VideoStreamTrack):
    def __init__(self, height, width, color):
        video_data_bgr = numpy.zeros((height,width,3),numpy.uint8)
        print(f"Debug: Shape of the video data array: {video_data_bgr.shape}")
        video_data_bgr[:,:] = color
        self.frame = frame_from_bgr(video_data_bgr)
    async def recv(self):
        return self.frame

**#Added a method for web cam in the cli.py**

async def video_cam(pc):
  cap = cv2.VideoCapture(0)
  n = 0
  while n <= 10:
    _,frame = cap.read()
    b,g,r = cv2.split(frame)
    _width = frame.shape[1]
    _height = frame.shape[0]
    camera_video = CombinedVideoStreamTrack(tracks=[
      CameraVideoStreamTrack(width=_width,height=_height,color=b.reshape(_height,_width,1)),
      CameraVideoStreamTrack(width=_width,height=_height,color=g.reshape(_height,_width,1)),
      CameraVideoStreamTrack(width=_width,height=_height,color=r.reshape(_height,_width,1))
    ])
    pc.addTrack(camera_video)
    await asyncio.sleep(1)
    n += 1
  cap.release()
  cv2.destroyAllWindows()

**#Added following call at the end of the run_offer function in the cli.py**

await video_cam(pc)

My understanding was since I am calling my coroutine function at the end of the run_offer, by that time the singling would have been setup and following method on_track will get a callback for every frame added to the track.

async def run_answer(pc, signaling):
    remote_track = None

    @pc.on('track')
    def on_track(track):
        nonlocal remote_track
        assert track.kind == 'video'
        print('Received video frame...')
        remote_track = track

But it is not happening. It is only getting the call back for he first dummy example track which was called synchronously at the beginning of the run_offer and nothing after it.

width = 320
    height = 240
    local_video = CombinedVideoStreamTrack(tracks=[
        ColorVideoStreamTrack(width=width, height=height, color=RED),
        ColorVideoStreamTrack(width=width, height=height, color=RED),
        ColorVideoStreamTrack(width=width, height=height, color=BLUE),
    ])
    pc.addTrack(local_video)

I really want to learn it and make it work. Could you please be kind to advise me what I am doing wrong ?
Thank you.

**Comment by jlaine** [comment]
I strongly suggest you switch to aiortc 0.9.9 and check out the "webcam" example, which uses the higher-level `MediaPlayer` API to play from a webcam.

There have been some significant changes to the media API, notably:

- the `VideoFrame` class is now PyAV's
- `MediaStreamTrack` subclasses need to populate the frame's timing information (`pts` and `time_base`) for accurate timestamping

I don't really have the manpower to support older `aiortc` versions.
