### ISSUE TITLE
Firefox fails in server example if remote

### ISSUE THREAD

**Issue by nfeybesse** [jlaine/aiortc#81]
Hi, I'm trying to run the server example from a remote browser.
It works with Chrome once the server is secured, but not with Firefox. 
It works with Firefox across the local network but not outside.
Ice gathering state complete / Signaling state stable; but connection state failed.

On debug, firefox is not responding to:

INFO:ice:Connection(2) Check CandidatePair(('192.168.1.100', 44767) -> ('82.240.164.123', 40654)) State.FROZEN -> State.IN_PROGRESS
DEBUG:ice:Connection(2) protocol(2) > ('82.240.164.123', 40654) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'~\xd6\xfb\xd9~@\xd9\x98\x8a\x11\x92\xa0')

There are answers with chrome and the treatment continues without difficulties.

A timeout is triggered on server when it is firefox:
ERROR: asyncio: Task exception was never retrieved
future: <Task finished coro = <RTCPeerConnection .__ connect () done, defined at /home/middleware/.local/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py:543> exception = ConnectionError ('ICE negotiation failed ')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send (None)
  File "/home/middleware/.local/lib/python3.5/site-packages/aiortc/rtcpeerconnection.py", line 548, in __connect
    await iceTransport.start (self .__ remoteIce [transceiver])
  File "/home/middleware/.local/lib/python3.5/site-packages/aiortc/rtcicetransport.py", line 270, in start
    await self._connection.connect ()
  File "/home/middleware/.local/lib/python3.5/site-packages/aioice/ice.py", line 385, in connect
    raise ConnectionError ('ICE negotiation failed')

I do not understand what blocks firefox and what prevents it from working well.

**Comment by lgrahl** [comment]
That's to be expected as I don't see any STUN servers in the example code. Which makes it even more surprising that Chrome works. Maybe they apply default servers (which is acceptable from the spec's perspective).

**Comment by nfeybesse** [comment]
I have changed in client.js :
var pc = new RTCPeerConnection({"iceServers":[{"urls":["stun:stun.l.google.com:19302"]}]});
Perhaps that's why it's working with chrome and not with firefox.
I will try to configure a stun server. Should I configure this on both js and python peer connection ?

**Comment by nfeybesse** [comment]
aiortc runs in my case behind a box with a tcp port forwarding on ssl port.
I have already tried Friday an account from viagenie for stun without succes with firefox.
Why firefox would need a stun server and chrome not ?

**Comment by jlaine** [comment]
Because Chrome already *does* use a STUN server by default, even if you don't specify one :)

**Comment by jlaine** [comment]
Hm, adding a STUN server significantly slows down the startup time on Firefox, so maybe I should make it opt-in, or detect whether the web page was opened on localhost before enabling it?

**Comment by nfeybesse** [comment]
Jeremy, firefox don't send any response (don't receive any request ?) after : 
DEBUG:ice:Connection(2) protocol(2) > ('82.240.164.123', 40654) Message(message_method=Method.BINDING, message_class=Class.REQUEST, transaction_id=b'\xd6\xfb\xd9@\xd9\x98\x8a\x11\x92\xa0')

**Comment by lgrahl** [comment]
Easiest is probably to go to `about:webrtc`, clear the history, try again, then click *Save Page* and attach it here.

**Comment by nfeybesse** [comment]
Voici

Statistiques de session

[ 2147494394 ] https://www.middlewareservices.com/ Sun Oct 14 2018 21:58:55 GMT+0200 (CEST)

Identifiant PeerConnection: 1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)
Statistiques ICE

Candidat local	Candidat distant	ID du composant	État ICE	Priorité	Nommé	Sélectionné	Octets envoyés	Octets reçus
192.168.1.101:42705/udp(host)	192.168.1.100:47336/udp(host)	1	failed	9115005270299247000	false	false	0	0

Redémarrages ICE: 0
Restaurations ICE: 0
Tous les candidats bruts

Candidat brut local	Candidat brut distant
host(IP4:192.168.1.101:42705/UDP)	candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host
host(IP4:192.168.1.101:59442/TCP) active	
srflx(IP4:192.168.1.101:42705/UDP|stun.l.google.com:19302)	
SDP

SDP local (Proposition)

v=0
o=mozilla...THIS_IS_SDPARTA-62.0 3846614218833461416 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 62:61:F1:47:D4:5F:FC:C5:76:E7:2D:0B:B1:6C:DA:0D:CB:9A:1D:2E:FD:74:3A:D3:BE:0F:E3:01:8C:96:54:14
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 42705 UDP/TLS/RTP/SAVPF 120 121 126 97
c=IN IP4 82.240.164.123
a=candidate:0 1 UDP 2122252543 192.168.1.101 42705 typ host
a=candidate:2 1 TCP 2105524479 192.168.1.101 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 192.168.1.101 50644 typ host
a=candidate:2 2 TCP 2105524478 192.168.1.101 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 82.240.164.123 42705 typ srflx raddr 192.168.1.101 rport 42705
a=candidate:1 2 UDP 1686052862 82.240.164.123 50644 typ srflx raddr 192.168.1.101 rport 50644
a=sendrecv
a=end-of-candidates
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:121 max-fs=12288;max-fr=60
a=ice-pwd:49255e132d78544e8a58d15705fde971
a=ice-ufrag:03b99219
a=mid:sdparta_0
a=msid:{85114b94-d3d2-4e3b-aa10-4e73dbb0f987} {4de9e582-c070-49eb-a2bc-b78b793c7d05}
a=rtcp:50644 IN IP4 82.240.164.123
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:121 VP9/90000
a=rtpmap:126 H264/90000
a=rtpmap:97 H264/90000
a=setup:actpass
a=ssrc:3055910539 cname:{04140339-9f4a-4cf2-a682-59c79db8ad3e}
SDP distant (Réponse)

v=0
o=- 3748535913 3748535913 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=group:BUNDLE sdparta_0
m=video 47336 UDP/TLS/RTP/SAVPF 120 126
c=IN IP4 192.168.1.100
a=candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host
a=candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 1694498815 80.11.169.204 47336 typ srflx
a=sendrecv
a=end-of-candidates
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=fingerprint:sha-256 C8:BD:55:5A:E6:27:BE:48:A8:A6:F9:07:45:31:C7:96:98:56:B9:D4:63:7B:28:14:77:FF:05:90:70:4A:5B:B0
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:H5QSzbBQ1vSf8RD8u7dMyQ
a=ice-ufrag:G9jE
a=mid:sdparta_0
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 goog-remb
a=rtcp-fb:126 nack
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=rtpmap:126 H264/90000
a=setup:active
a=ssrc:2975345660 cname:{5e1bf333-19c8-4b72-9b82-af498afdc7d3}
Statistiques RTP

outbound_rtcp_video_0

Local: 14:18:57 GMT+0100 (CET) inbound-rtp SSRC: 3055910539

inbound_rtp_video_1

Local: 21:58:55 GMT+0200 (CEST) inbound-rtp SSRC: 3369396861

outbound_rtp_video_0

Local: 21:58:55 GMT+0200 (CEST) outbound-rtp SSRC: 3055910539

Distant: 14:18:57 GMT+0100 (CET) inbound-rtp SSRC: 3055910539

Historique de connexion

/build/firefox-8oo9jx/firefox-62.0+build2/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/build/firefox-8oo9jx/firefox-62.0+build2/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): failed to create passive TCP host candidate: 3

/build/firefox-8oo9jx/firefox-62.0+build2/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/build/firefox-8oo9jx/firefox-62.0+build2/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): failed to create passive TCP host candidate: 3

STUN-CLIENT(srflx(IP4:192.168.1.101:42705/UDP|stun.l.google.com:19302)): Received response; processing

STUN-CLIENT(srflx(IP4:192.168.1.101:50644/UDP|stun.l.google.com:19302)): Received response; processing

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): Error parsing attribute: candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 1694498815 80.11.169.204 47336 typ srflx

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): peer (PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default) specified bogus candidate

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/CAND-PAIR(TGm0): setting pair to state FROZEN: TGm0|IP4:192.168.1.101:42705/UDP|IP4:192.168.1.100:47336/UDP(host(IP4:192.168.1.101:42705/UDP)|candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host)

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/))/CAND-PAIR(TGm0): Pairing candidate IP4:192.168.1.101:42705/UDP (7e7f00ff):IP4:192.168.1.100:47336/UDP (7effffff) priority=9115005270299246590 (7e7f00fffdfffffe)

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/CAND-PAIR(TGm0): setting pair to state WAITING: TGm0|IP4:192.168.1.101:42705/UDP|IP4:192.168.1.100:47336/UDP(host(IP4:192.168.1.101:42705/UDP)|candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host)

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/ICE-STREAM(0-1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/) aLevel=0): Starting check timer for stream.

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/CAND-PAIR(TGm0): setting pair to state IN_PROGRESS: TGm0|IP4:192.168.1.101:42705/UDP|IP4:192.168.1.100:47336/UDP(host(IP4:192.168.1.101:42705/UDP)|candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host)

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): peer (PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default) is now checking

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): peer (PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default) no streams with pre-answer requests

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default): no pairs for 0-1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/) aLevel=0

ICE(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/)): peer (PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default) Trickle grace period is over; marking every component with only failed pairs as failed.

STUN-CLIENT(TGm0|IP4:192.168.1.101:42705/UDP|IP4:192.168.1.100:47336/UDP(host(IP4:192.168.1.101:42705/UDP)|candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host)): Timed out

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/CAND-PAIR(TGm0): setting pair to state FAILED: TGm0|IP4:192.168.1.101:42705/UDP|IP4:192.168.1.100:47336/UDP(host(IP4:192.168.1.101:42705/UDP)|candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 2130706431 192.168.1.100 47336 typ host)

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default)/STREAM(0-1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/) aLevel=0)/COMP(1): All pairs are failed, and grace period has elapsed. Marking component as failed.

ICE-PEER(PC:1539547106226447 (id=2147494394 url=https://www.middlewareservices.com/):default): all checks completed success=0 fail=1

+++++++ END ++++++++

**Comment by lgrahl** [comment]
@jlaine That's interesting

```
Error parsing attribute: candidate:8a40640bad8897189d098d1ad6ba3a3a 1 udp 1694498815 80.11.169.204 47336 typ srflx
```

**Comment by jlaine** [comment]
Hm I don't think "raddr" is supposed to be mandatory.. but:

https://dxr.mozilla.org/mozilla-central/source/media/mtransport/third_party/nICEr/src/ice/ice_parser.c#252

**Comment by lgrahl** [comment]
From https://tools.ietf.org/html/rfc5245#section-15.1:

> \<rel-addr> and \<rel-port>:  convey transport addresses related to the
> candidate, useful for diagnostics and other purposes. **\<rel-addr>
> and \<rel-port> MUST be present for server reflexive, peer
> reflexive, and relayed candidates.**  If a candidate is server or
> peer reflexive, \<rel-addr> and \<rel-port> are equal to the base
> for that server or peer reflexive candidate.  If the candidate is
> relayed, \<rel-addr> and \<rel-port> is equal to the mapped address
> in the Allocate response that provided the client with that
> relayed candidate (see Appendix B.3 for a discussion of its
> purpose).  If the candidate is a host candidate, \<rel-addr> and
> \<rel-port> MUST be omitted.

**Comment by jlaine** [comment]
I was reading exactly that. OK, this sucks ands needs to be addressed in aioice ASAP.

**Comment by nfeybesse** [comment]
Exact, I had not updated aiortc but only aioice.
It's working now ! 
Congratulations for your library and thank you for your reactivity!
