### ISSUE TITLE
QUESTION[Trying videostream_cli example in separate hosts linux environment]

### ISSUE THREAD

**Issue by sarkarchandan** [jlaine/aiortc#83]
Hi Jeremy,

I am trying aortic framework examples, specifically the videostream_cli example in docker.
Before that I have tried the videostream_cli example in a my machine (instantiating MediaPlayer with a dummy video file) with the following arguments

command-line window 1 > python cli.py --signaling tcp-socket --signaling-host 0.0.0.0 --signaling-port 8888 offer
command line window 2 > python cli.py --signaling tcp-socket --signaling-host 0.0.0.0 --signaling-port 8888 --record-to received.mp4 answer

Having MediaPlayer api instantiated with a dummy video file it worked without any issues.

Now I am trying the same in linux machine using docker.
I am instantiating the MediaPlayer with ('/dev/video0' options={'video_size':'vga'}) as you suggested in the media.py

I have also noticed that TCPSocketSignalling class attempts the asyncio.start_server method with the passed in host and port number. So far in the example everything was happening in the local host. So my understanding is localhost was my singling server between offer and answer peers.

My general question is when we have two separate hosts to execute offer and answer how the arguments should look like ?

Assuming IP addresses of two hosts are offer:172.31.0.1 and answer:172.31.0.2 can the --signaling-host be a third host now e.g --signaling-host 172.31.0.3 ?
Like

offer:172.31.0.1 command line > python cli.py --signaling tcp-socket --signaling-host 172.31.0.3 --signaling-port 8888 offer
answer:172.31.0.2 command line > python cli.py --signaling tcp-socket --signaling-host 172.31.0.3 --signaling-port 8888 --record-to received.mp4 answer

Is that correct or I am thinking something fundamentally wrong ?
Thanks a lot.

**Comment by jlaine** [comment]
Hi! The signaling examples provided with aiortc are intended to be "low setup", as experience shows asking users to set up a signaling server is usually confusing and error prone. So for the TCP example you mentioned, the offerer arbitrarily takes on the "server" role, and the answerer the "client" role - there is no provision for signaling to be hosted on a third host.

In your case you are probably looking for:

offer : `python cli.py --signaling tcp-socket --signaling-host 172.31.0.1 --signaling-port 8888 offer`
answer: `python cli.py --signaling tcp-socket --signaling-host 172.31.0.1 --signaling-port 8888 answer`

If you want an example which uses a third host to mediate signaling, I suggest you look at the "apprtc" demo which uses https://appr.tc/ to provide signaling.

**Comment by sarkarchandan** [comment]
Thanks a lot Jeremy, that answers my question.

**Comment by jlaine** [comment]
Great! If you would like to contribute some improvements to the docs or examples, you are most welcome to open a PR

**Comment by sarkarchandan** [comment]
Thanks. I am currently experimenting with the webcam example. I have been able to tweak and execute the webcam example in separate docker containers. 
I am working on creating a functional IoT application prototype using aiortc. Once that is done I would be happy to contribute it as an example if you are ok with it.
