### ISSUE TITLE
Streaming H264 compressed frames

### ISSUE THREAD

**Issue by bjschwa2** [jlaine/aiortc#84]
I am trying to send compressed h264 frames from a camera into a VideoStreamTrack object and have it viewed in a browser client. I believe the webcam example is the closest to what I am trying to accomplish except instead of reading from a file I have the frames in memory from an object. 

```python
                # change the frame pointer into a byte array (this works)
                myCArray = ctypes.cast(int(frame.Data()), ctypes.POINTER(ctypes.c_char * frame.Size()))[0]
                myArray  = bytearray(myCArray)

                # create a numpy array from the byte array
                array = numpy.fromstring(b''+myArray, dtype=numpy.uint8) 
                return VideoFrame.from_ndarray(array, format='h264')
```
I get the following error which I believe is due to the fact that I am passing in compressed data (which is a single dimension).
```
Task exception was never retrieved
future: <Task finished coro=<RTCRtpSender._run_rtp() done, defined at /home/bradley/src/aiortc/venv/lib/python3.5/site-packages/aiortc/rtcrtpsender.py:239> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/bradley/src/aiortc/venv/lib/python3.5/site-packages/aiortc/rtcrtpsender.py", line 256, in _run_rtp
    self.__stopped.wait())
  File "/home/bradley/src/aiortc/venv/lib/python3.5/site-packages/aiortc/utils.py", line 73, in first_completed
    return task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/bradley/src/aiortc/venv/lib/python3.5/site-packages/aiortc/rtcrtpsender.py", line 217, in _next_encoded_frame
    frame = await self.__track.recv()
  File "webcam.py", line 173, in recv
    return VideoFrame.from_ndarray(array, format='h264')
  File "av/video/frame.pyx", line 300, in av.video.frame.VideoFrame.from_ndarray
AssertionError
```
Any suggestions how passing along already compressed frames can be accomplished with aiortc?

**Comment by jlaine** [comment]
Hi Bradley,

Unfortunately, you cannot just send already encoded H.264 packets with aiortc. Its media pipeline is designed to operate on decoded frames (PyAV's VideoFrame class), and these are encoded with whatever codec was negotiated with the remote party (usually VP8) just before RTCRtpSender sends them over SRTP.

If you want you can use PyAV to decode your H.264 packets into VideoFrames and then feed them to aiortc (the MediaPlayer class itself is a wrapper around PyAV). The alternative is to hack RTCRtpSender to take pre-encoded H.264 data, but that's going to be trickier as you will need to deal with packetization yourself.

**Comment by jlaine** [comment]
Tip: `VideoFrame.from_ndarray` expects decode pixel data, only in rgb24 format for PyAV < 6.0.0, or in several other formats starting with PyAV 6.0.0:

https://github.com/mikeboers/PyAV/blob/88dff2cae78e1ce000d9f730dd2a3d9bd4dc9e54/av/video/frame.pyx#L386
