### ISSUE TITLE
Receiving AttributeError: 'RTCRtpTransceiver' object has no attribute '_codecs' when attempting to add audio track to the webcam example

### ISSUE THREAD

**Issue by benwilber** [jlaine/aiortc#86]
I have modified the webcam example to play a [local MP4 file](https://ll-streams.s3.amazonaws.com/colorbars.mp4) that contains an H.264 video track, and an AAC audio track.

I have modified the [webcam.py](https://github.com/jlaine/aiortc/blob/master/examples/webcam/webcam.py#L41) example like:

```python
player = MediaPlayer('colorbars.mp4')
pc.addTrack(player.video)
pc.addTrack(player.audio)
```

However, once it calls `pc.createAnswer()` I get the following exception:

```shell
$ python webcam.py 
======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
Error handling request
Traceback (most recent call last):
  File "/Users/benw/.virtualenvs/aiortc/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/Users/benw/.virtualenvs/aiortc/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "webcam.py", line 46, in offer
    answer = await pc.createAnswer()
  File "/Users/benw/.virtualenvs/aiortc/lib/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 306, in createAnswer
    sdp=self.__createSdp('answer'),
  File "/Users/benw/.virtualenvs/aiortc/lib/python3.6/site-packages/aiortc/rtcpeerconnection.py", line 631, in __createSdp
    fmt=[c.payloadType for c in transceiver._codecs])
AttributeError: 'RTCRtpTransceiver' object has no attribute '_codecs'
```

This does not happen if I just add the video track, not the audio track.

**Comment by jlaine** [comment]
The root cause is you cannot just blindly add the track to without looking at the offer. The offer which comes from the browser only offers to receive video, not audio:

https://github.com/jlaine/aiortc/blob/bca84180a3d2cd0d9a185270874c970c2e646eb7/examples/webcam/client.js#L15

I will however check how I can update the `RTCPeerConnection` code to ignore the extra track when generating the response.

**Comment by benwilber** [comment]
makes sense now thank you!
