### ISSUE TITLE
rtp forwarding

### ISSUE THREAD

**Issue by sbeneduce** [jlaine/aiortc#88]
#Can i forward rtp to ffmpeg or gstreamer?

i think i need to extend _handle_rtp_packet method of class RTCRtpReceiver:

when i reach this point:

line 362 
if we have a complete encoded frame, decode it
	            if encoded_frame is not None and self.__decoder_thread:
	                encoded_frame.timestamp = self.__timestamp_mapper.map(encoded_frame.timestamp)
	                self.__decoder_queue.put((codec, encoded_frame))

i decode the frame
line 40
 	        for frame in decoder.decode(encoded_frame):
	            # pass the decoded frame to the track
	            asyncio.run_coroutine_threadsafe(output_q.put(frame), loop)

instead that passing to the track, i need to pass it to ffmpeg or gstreamer ... but how?

it would be great to have player, writer and also streamer class

**Comment by jlaine** [comment]
I don't understand why you would want to do this, could you elaborate?

Have you looked at the MediaPlayer and MediaRecorder classes? These are wrappers against PyAV.. which uses libav*

**Comment by sbeneduce** [comment]
I would like to take the stream from the browser and to pass to ffmpeg to stream in rtmp (youtube ..).

Pyav do not allow it.

I would like to replicate the rtp forwarding of Janus

**Comment by jlaine** [comment]
Again, I'll repeat my question: MediaRecorder *is* ffmpeg-based, so you can leverage the full power of FFmpeg from within aiortc (rtmp, whatever). What more do you need?

**Comment by sbeneduce** [comment]
Mediarecorder is based on pyav tha has one method av.open an it can just read or write files. It is not a full ffmpeg wrapper (i was thinking on how to swap pyav with ffmpy)

class MediaRecorder:
    """
    A media sink that writes audio and/or video to a file.
    Examples:
    .. code-block:: python
        # Write to a video file.
        player = MediaRecorder('/path/to/file.mp4')
        # Write to a set of images.
        player = MediaRecorder('/path/to/file-%3d.png')
    :param: file: The path to a file, or a file-like object.
    :param: format: The format to use, defaults to autodect.
    :param: options: Additional options to pass to FFmpeg.
    """
    def __init__(self, file, format=None, options={}):
        self.__container = av.open(file=file, format=format, mode='w', options=options)
        self.__tracks = {}

I cannot use it. If i am wrong can you pos a sample that streams to a youtube endpoint?

Thanks

**Comment by sbeneduce** [comment]
Mediarecorder is based on pyav tha implements only a method  av.open that allows to read and write files

av.open(file, mode='r', format=None, options=None, metadata_encoding=None, metadata_errors='strict')¶

And media recorder implements it as follows

class MediaRecorder:
    """
    A media sink that writes audio and/or video to a file.
    Examples:
    .. code-block:: python
        # Write to a video file.
        player = MediaRecorder('/path/to/file.mp4')
        # Write to a set of images.
        player = MediaRecorder('/path/to/file-%3d.png')
    :param: file: The path to a file, or a file-like object.
    :param: format: The format to use, defaults to autodect.
    :param: options: Additional options to pass to FFmpeg.
    """
    def __init__(self, file, format=None, options={}):
        self.__container = av.open(file=file, format=format, mode='w', options=options)
        self.__tracks = {}

I need to call ffmpeg to execute something like:

ffmpeg \
    -i "$SOURCE" -deinterlace \
    -vcodec libx264 -pix_fmt yuv420p -preset $QUAL -r $FPS -g $(($FPS * 2)) -b:v $VBR \
    -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k \
    -f flv "$YOUTUBE_URL/$KEY"

That's why i was thinking to use ffmpy instead of pyav

How can i do it? 

The reason why i was thinking to forward rtp to ffmpeg was to reduce latency

**Comment by jlaine** [comment]
FFmpeg is just a command line tool over libav*. PyAV is a pythonic binding to these exact same libraries. I've pointed you to the easiest / most efficient option: MediaRecorder.

I haven't tried myself but I imagine what you want is something like:

`MediaRecorder(your_url, format='flv', options={..})`

You've already decided you want to use something else? Fine by me, just don't expect free consulting work.

**Comment by sbeneduce** [comment]
thanks
