### ISSUE TITLE
run aiortc on https

### ISSUE THREAD

**Issue by blinkbink** [jlaine/aiortc#92]
Hello, i try running examples/server/server.py in HTTPS mode, 
```
    parser = argparse.ArgumentParser(description='WebRTC audio / video / data-channels demo')
    parser.add_argument('--port', type=int, default=5111, help='Port for HTTP server (default: 8080)')
    parser.add_argument('--verbose', '-v', action='count')
    parser.add_argument('--write-audio', help='Write received audio to a file')
    args = parser.parse_args()

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG)

    app = web.Application()
    app.on_shutdown.append(on_shutdown)
    app.router.add_get('/', index)
    app.router.add_get('/client.js', javascript)
    app.router.add_post('/offer', offer)
    web.run_app(app, port=args.port)
```

i add : `web.run_app(app, port=args.port, ssl_context=('cert.pem', 'key.pem'))` for ssl certificate, but i can''t access it from https://localhost:5111 but when i remove ssl_context then run http://localhost:5111 it's work. 
got error :` aiohttp.http_exceptions.BadStatusLine: invalid HTTP method` when access with removed ssl_context and accest with https.
can i run in HTTPS mode, what i do is i want to access this from another side, client ?

**Comment by jlaine** [comment]
This is unrelated to `aiortc`, I suggest you read the `aiohttp` documentation, as it states that `ssl_context` must be an `ssl.SSLContext` not a tuple:

https://docs.aiohttp.org/en/stable/web_reference.html?highlight=ssl#aiohttp.web.run_app

**Comment by jlaine** [comment]
I added command line options to set the SSL cert and key in 6c0dc49e302c4687ba6de929e12bd5c0a2a98bdd
