### ISSUE TITLE
long time no response when installing aiortc

### ISSUE THREAD

**Issue by baudzhou** [jlaine/aiortc#95]
env: ubuntu 16.04(vm), python 3.6.6
when installing aiortc using 'pip install aiortc', I waited for more than half an hour. And I had to 'ctr+c' to terminate.  Then I tried to clone the source to install manually, but still got the same problem.
Hope anybody could help, thx!

**Comment by jlaine** [comment]
Could you at least include some output, as there is really nothing to investigate here?

**Comment by jlaine** [comment]
No answer from hit-and-run submitter, closing.
