### ISSUE TITLE
Allow ordered:false and maxRetransmits:0 (unreliable) createDataChannel parameters

### ISSUE THREAD

**Issue by inactivist** [jlaine/aiortc#96]
Does AIORTC support unordered/unreliable data channels with no retransmits?  I'd like to create a data channel that simply drops undelivered messages.

I've been experimenting with data channels, trying to use various "UDP-like" configurations as described in [this blog post](https://jameshfisher.com/2017/01/17/webrtc-datachannel-reliability.html) (or, using slightly older docs, [this section of High Performance Browser Networking](https://hpbn.co/webrtc/#configuring-message-order-and-reliability)), but I've been unsuccessful so far.

I created a branch off 0.9.12 and [modified your server example `client.js` and `index.html`](https://github.com/inactivist/aiortc/tree/testing-udplike-datachannel-opts/examples/server) to allow setting these alternate `createDataChannel()` options:

```javascript
{
    ordered: false,
    maxRetransmits: 0
};
```
Referring to [my fork/branch](https://github.com/inactivist/aiortc/tree/testing-udplike-datachannel-opts/examples/server): When using the alternate options it connects but never receives 'pong' responses from server.py:

```
*** Creating data channel with options={"ordered":false,"maxRetransmits":0}
- open
> ping
> ping
...
> ping
> ping
- close
```

Questions:

1. Am I doing something wrong as far as WebRTC spec, or is this something that `aiortc` simply doesn't support at this time?  
2. Are there any RTCDataChannel option combinations that will work to disable data channel re-transmits in `aiortc`?

Also: Thanks for your efforts on `aiortc` -- I've been experimenting with it for a while now, and it's been very helpful so far.  I'd be glad to help with development/debugging as appropriate.

## Version info:
AIORTC 0.9.12
Chrome Version 70.0.3538.102 (Official Build) (64-bit)
Firefox Version 63.0 (64-bit)
Python 3.6.6
Ubuntu 16.04.5 LTS w/4.15.0-39-generic kernel

**Comment by jlaine** [comment]
Currently only ordered data channels are implemented. It's probably not a huge deal to implement the unordered mode, but I haven't had the usecase yet.

**Comment by inactivist** [comment]
Ok.  Let me know if I can help, as it's something I will need for an app I'm working on.

**Comment by jlaine** [comment]
I am currently refactoring the `InboundStream` class to support unordered delivery. I'm not sure yet what support for unreliable delivery entails, feel free to dig into SCTP's RFC:

https://tools.ietf.org/html/rfc4960

**Comment by lgrahl** [comment]
On a high level: In unordered mode, you can have reordered messages but there is no interleaving of messages (i.e. interleaved delivery of chunks from different messages).

**Comment by jlaine** [comment]
@inactivist I have just pushed a commit that fixes the interoperability issue you reported. The message delivery still needs fixing to actually be unordered, but at least you will now receive the messages.

**Comment by inactivist** [comment]
Doing a quick test, using the 0.9.14 release tag, it appears I can use the specified parameters to create a data channel in Firefox but not Chrome (the client.js cd.onopen handler never fires, but no server-side errors.)  Will investigate further.

**Comment by inactivist** [comment]
I changed the title to be more relevant to the observed failure.

**Comment by inactivist** [comment]
>  feel free to dig into SCTP's RFC

Will do so when time permits, probably in a few weeks. 

Related question: Is there a simple way to patch `aiortc` so that data channels are always "unreliable" (unordered, no retransmit, no buffering) so basically, the sender never re-transmits errors, and receiver never notifies sender about dropped messages.  I'm looking for a very quick and dirty / hackish way to validate behavior in that scenario.

Here's my use case driving : I'm testing WebRTC datachannel suitability for high-throughput, low-latency data delivery on a LAN/WiFi.  I want to understand/validate unreliable datachannel behavior when connection quality declines.  The desired behavior is that the messages are simply dropped, so the receiver never waits for re-transmit.

I'm locked on the 0.9.13 version at the moment, ran in to some issues when I tried to move to 0.9.14+, will try to do that when time permits.

**Comment by jlaine** [comment]
There is no "hack" for magically getting unordered / no retransmit mode, if you need it you really do need to go and implement it.

- unordered delivery : this involves tweak or re-writing the InboundStream class (and writing plenty of tests):

https://github.com/jlaine/aiortc/blob/4614d495c912bef3bf91e297a6351ce31c7b8774/aiortc/rtcsctptransport.py#L457

- limiting / disabling retransmissions is another kettle of fish, AFAICT it means implementing RFC 3758:

https://tools.ietf.org/html/rfc3758

This allows the sender to instruct the receiver to "give up" on some some missing data chunks

**Comment by inactivist** [comment]
> There is no "hack" for magically getting unordered / no retransmit mode, if you need it you really do need to go and implement it.

Thanks for the feedback - the pointers are very much appreciated. Will investigate when time permits.

**Comment by jlaine** [comment]
Let's keep this issue open to track the lack of support for unordered / max retransmits, I've got some pending code.

**Comment by jlaine** [comment]
OK, so with the latest code on master, `aiortc`:

- implements unordered delivery
- supports partial reliability *on the receiver side*. You can try this out with the `server` example which provides a drop-down allowing you to choose "Unordered, no retransmissions".

To try this out I apply a local hack which randomly drops DATA chunks:

```patch
diff --git a/aiortc/rtcsctptransport.py b/aiortc/rtcsctptransport.py
index d2b2df2..e289901 100644
--- a/aiortc/rtcsctptransport.py
+++ b/aiortc/rtcsctptransport.py
@@ -4,6 +4,7 @@ import hmac
 import logging
 import math
 import os
+import random
 import time
 import warnings
 from struct import pack, unpack, unpack_from
@@ -929,7 +930,10 @@ class RTCSctpTransport(EventEmitter):
 
         # common
         elif isinstance(chunk, DataChunk):
-            await self._receive_data_chunk(chunk)
+            if random.random() < 0.8:
+                await self._receive_data_chunk(chunk)
+            else:
+                print('DROP')
         elif isinstance(chunk, SackChunk):
             await self._receive_sack_chunk(chunk)
         elif isinstance(chunk, HeartbeatChunk):
```

**Comment by inactivist** [comment]
This is really excellent, thanks for that.  I'll try to test it out in my environment soon and provide feedback.
