### ISSUE TITLE
How to use server example with https

### ISSUE THREAD

**Issue by ajmal-adfg** [jlaine/aiortc#97]
Hi,

I want to use the aiortc over https instead of using it https. how can i use it?

Thanks,
Ajmal

**Comment by jlaine** [comment]
I assume you are referring to the "server" example? If so please refer to the `aiohttp` documentation, it explains how to use an `SSLContext`.

**Comment by ajmal-adfg** [comment]
yes. i want to use the server example and want to send the data to browser over HTTPS instead of HTTP.
