### ISSUE TITLE
OpenCV VideoStreamTrack not working

### ISSUE THREAD

**Issue by tobiasfriden** [jlaine/aiortc#99]
Hello,

Trying to use `cv2.VideoCapture` to stream the webcam from my Mac (since I cannot just use MediaPlayer with ´/dev/video0´).

I implemented a class like this:
```python
class WebCamTrack(VideoStreamTrack):
    def __init__(self):
        super().__init__()
        self.cap = cv2.VideoCapture(0)

    async def recv(self):
        pts, time_base = await self.next_timestamp()
        ret, frame = self.cap.read()
        vf = VideoFrame.from_ndarray(frame)
        vf.pts = pts
        vf.time_base = time_base
        return vf
```

However, I am getting `TypeError: cannot unpack non-iterable int object` at `pts, time_base = await self.next_timestamp()`. Substituting with `print(await self.next_timestamp())` I can see it just returns 0, instead of two values.

Edit: I have aiortc v 0.9.8 installed.

**Comment by jlaine** [comment]
Please install the latest aiortc (0.9.12) and report back, APIs have changed and you cannot just grab the latest examples and run them against an old aiortc.

On what you are trying to achieve : I don't recommend using cv2.VideoCapture as you are doing, it is incapable of giving you the correct timestamps. I'd rather we make the necessary adjustements to MediaPlayer to make it work on Mac.

**Comment by jlaine** [comment]
Let's focus on the original issue, if you have another issue let's track it separately.

Could you please confirm the correct syntax for using MediaPlayer with a webcam on OS X so that I can include it in the documentation?

**Comment by tobiasfriden** [comment]
Ok sure, I'll submit a separate issue.

Actually seems to be possible using `MediaPlayer` on mac but you have to use `ffmpeg` to stream the webcam to a file.

First start stream with:
`ffmpeg -f avfoundation -framerate 30 -i "0" out.mpg`
Then it can be used as `MediaPlayer('out.mpg')`

**Comment by jlaine** [comment]
@tobiasfriden can you please answer my questions? I don't have access to an OS X machine so you feedback is important.

MediaPlayer *is a wrapper around the ffmpeg libraries*, so the equivalent of what you sent would be:

`MediaPlayer('0', format='avfoundation', options={'framerate': '30'})`

**Comment by tobiasfriden** [comment]
Aha, cool! Did not understand it could be used like that that yet.
Using that it seems to be able to capture and send the video stream from aiortc.
However when using that aproach the `MediaTrack` in the browser never switches from `muted` (when using my approach with OpenCV it does after about ~1.5 min).

However, I am using a self implemented SFU in between so it the fault might be on my side.
I will do some more debugging and submit another issue if my implementation is working.
I can test using that approach with direct p2p between browser and aiortc as well.

**Comment by jlaine** [comment]
The best test which *only* tests aiortc is to:

- install aiortc 0.9.13 (just released)
- run the "webcam" example
- point your browser to http://localhost:8080

-> do you see your webcam's video?

**Comment by tobiasfriden** [comment]
Yes, that works with `MediaPlayer('0', format='avfoundation', options={'framerate': '30'})`. However there is quite large latency in the displayed video.
